### ISSUE TITLE
Proposal: new settings UI

### ISSUE THREAD

**Issue by FineFindus** [LucasGGamerM/moshidon#103]
The current settings UI is quite horrible in terms of UX. It only consists of a long list of sections with different settings. Often times it's not even clear, why some settings fall into one section, but not the other, for example the uniform notification icon could also fit into the Notification section, the hide compose button could also be in the Timelines section, etc…. Settings are often ambiguous to understand from just the title alone, without any additional description to help. And there is not even a way to search for a specific setting.

To improve the situation, I propose a new settings UI with subpages instead of sections. This would leave more space for each section, providing space for an explanation underneath, or possible a visual above, similar to the theme preference.

**Comment by LucasGGamerM** [comment]
That is indeed a much needed improvement

**Comment by LucasGGamerM** [comment]
That is indeed a much needed improvement. But, do you have any mockups? I am not sure how I should go about adding submenus to the settings and still making them organized

**Comment by FineFindus** [comment]
Sadly no. I think keeping the current sections is fine for now, I would just move the submenus under the sections to their own page.

**Comment by LucasGGamerM** [comment]
Next update is gonna have a refactored settings page. Gonna close this one for now
