### ISSUE TITLE
Add the ability to reorder notification actions 

### ISSUE THREAD

**Issue by LucasGGamerM** [LucasGGamerM/moshidon#104]
I would love to have a setup like: reply, favorite and dismiss, but the way that the current @FineFindus implementation does, the actions are static. This would be something awesome to have.

**Comment by FineFindus** [comment]
I disagree, I think the ability to reorder them, only adds unnecessary maintenance cost, without any value, it doesn't really matter if one of the buttons is a few more pixels left or right. I think it would be way more valuable to have the ability to turn them on or off, but I would like for #103 to be resolved first, as this would only add even more settings.

**Comment by LucasGGamerM** [comment]
I meant on the notification actions, not inside the actual app

**Comment by FineFindus** [comment]
I'm a bit confused now, could a please describe in more detail what you want/ include mock-ups if possible. Also, `dismiss` shouldn't be an action, it's already provided by the system by swiping the notification away.

**Comment by LucasGGamerM** [comment]
I will make do something later

**Comment by LucasGGamerM** [comment]
I am already making some progress in adding a reply button, its almost done i think. The only issue I have encountered is not being able to close the notification tray after clicking at the reply button in the notification.

**Comment by FineFindus** [comment]
I thought you didn't want one ‽ Otherwise I would have added one.

**Comment by FineFindus** [comment]
OK, in that case, I will add one tomorrow
