### ISSUE TITLE
bug(custom-timelines): Profile lookup fails

### ISSUE THREAD

**Issue by FineFindus** [LucasGGamerM/moshidon#107]
**Describe the bug**

Profile lookup fails in custom timelines, without opening the full post.

**To reproduce**

1. Go to a custom timelines
2. Click on an account mention, without opening the post
3. See error

**Does this happen in the official app?**

Does this issue also occur with the respective upstream release?

No, it doesn't have custom timelines

**Version**

Moshidon version: v1.2.0+fork.98.moshinda

**Comment by LucasGGamerM** [comment]
This has been quite the issue so far. While its an annoying thing, its easy enough to just click on the post before clicking on the mentions for now. It will be fixed soon enough though
