### ISSUE TITLE
Unreliable application of set filters

### ISSUE THREAD

**Issue by ffffennek** [LucasGGamerM/moshidon#109]
1. have a "whole word" filter for "home and lists" to "hide completely" the word "GOP"
2. follow @mmasnick@mastodon.social 
3. have moshidon 1.2.0+fork.98.moshinda-play (98) installed
4. scroll back to about 13 hours back before when I post this.

see this https://mastodon.social/@Popehat/109963111991422811 post boosted in your Home timeline in Moshidon even though it contains "GOP". (screenshot here https://cyberplace.social/@fennek/109966055583749840 )

`Does this issue also occur with the respective upstream release?`
I do not know, but I do assume so, since an earlier complaint with Megalodon regarding a very similar issue (filter worked in Home but not in a list)  https://cyberplace.social/@fennek/109759775406907880 was soon after followed by this https://floss.social/@megalodon/109777393792724752

Just FYI: I do not have the official app installed and no intention to do change that.

**Comment by LucasGGamerM** [comment]
Can you try adding another filter with the same keywords? I am not sure I can reproduce that bug, but I would be happy to help!

**Comment by ffffennek** [comment]
Unfortunately I do seldomly have time to do experiments. Today would be
good, but scrolling back to days ago is not really something i would like
to do even when I theoretically have the time.

Any suggestions on what (kind of) filters I could set today to trigger the
bug?

Just tried random German and English words from today's toots and
everything worked as intended.

LucasGGamerM ***@***.***> schrieb am So., 5. März 2023, 01:30:

**Comment by LucasGGamerM** [comment]
It seems to be fixed ever since the in app filter handling system was updated
