### ISSUE TITLE
Enable recents URL sharing

### ISSUE THREAD

**Issue by MKCOOL142** [LucasGGamerM/moshidon#119]
Since Android 12 Pixel launcher supports copying URLs from the recents screen. I'd love to see this be avaible in Moshidon as well and it doesn't seem like the most complicated thing ever but idk.

https://developer.android.com/guide/components/activities/recents#url-sharing

some open source apps like Nekogram support it if you want a code sample or something idk

**Comment by FineFindus** [comment]
It's a bit more involved that just overwriting this single method, as the app is actually just one activity with many fragments. I will try to implement int over the weekend.
