### ISSUE TITLE
Notifications overwrite each other

### ISSUE THREAD

**Issue by FineFindus** [LucasGGamerM/moshidon#129]
**Describe the bug**
Notifications sometimes replace each other, this usually does not happen immediately, only after the app hasn't been opened for a while.

**To reproduce**

1. Receive a notification
2. Wait a while
3. Receive a second notification
4. Notice how the first one is gone

**Version**

Moshidon version: 1.2.0+fork.99.moshinda

**Additional Context**
Usually, notifications replacing each other occurs when using the same id/tag again. That this only happens after a while supports the theory, that the app gets reset/ resets the notification ID in the background, which results in multiple notifications with the same ID.

**Comment by LucasGGamerM** [comment]
Its probably nice to put the ID on the Global user preferences and then look the next id there

**Comment by FineFindus** [comment]
Just beware that that would result in a maximum of `2 147 483 647` Notifications that could be sent per account.

**Comment by LucasGGamerM** [comment]
> Just beware that that would result in a maximum of `2 147 483 647` Notifications that could be recieved per account.

Not if I used a long unsigned int, which would be more than enough to count the particles in the universe
