### ISSUE TITLE
Search emojis

### ISSUE THREAD

**Issue by ronilaukkarinen** [LucasGGamerM/moshidon#13]
I'd like to be able to search emojis.

**Comment by LucasGGamerM** [comment]
Ok, this feature is available on the web client. Will see what can be done!

**Comment by ronilaukkarinen** [comment]
Kinda related: "Frequently used" is also something I'm missing, I kinda overuse it. Right now on Moshidon I need to use a lot of time to pick the emoji I want.

**Comment by LucasGGamerM** [comment]
If it's on the webclient, it can be done! It will be worked on soon

**Comment by ronilaukkarinen** [comment]
@LucasGGamerM I still don't see this?

**Comment by LucasGGamerM** [comment]
I must have closed this issue by accident

**Comment by FineFindus** [comment]
> I must have closed this issue by accident

No, I referenced it, when implementing the recent emoji feature, and github auto-closed when you merged the pr.

**Comment by LucasGGamerM** [comment]
Well, I have realized that you can already search emojis by tying ":" and searching just like a user or hashtag.
