### ISSUE TITLE
Can't login into mastodon.social - invalid_client error

### ISSUE THREAD

**Issue by KorneevVitaly** [LucasGGamerM/moshidon#14]
When I try to authorize into mastodon.social, I'm getting this error:
`{"error":"invalid_client","error_description":"Client authentication failed due to unknown client, no client authentication included, or unsupported authentication method."}`

**Comment by LucasGGamerM** [comment]
Huh? I dont have a mastodon.social account, so I cant debug it. But it works on both mas.to accounts and floss.social accounts. Can you please check if the bug occurs on the official client?

**Comment by KorneevVitaly** [comment]
Hmm... tried to open authorize in another browser, where I was not authorized and there was no such error. Strage... And this behavior was same in official browser. I think that mean I could close this issue.
