### ISSUE TITLE
Nightly APKs

### ISSUE THREAD

**Issue by leap0x7b** [LucasGGamerM/moshidon#141]
Could you possibly add a GitHub action workflow to build APKs?

**Comment by LucasGGamerM** [comment]
Yes! Some people on matrix have already shown interest in nightly builds. I will set them up later today

**Comment by LucasGGamerM** [comment]
You can now get nightly apks from here:
https://github.com/LucasGGamerM/moshidon/actions/workflows/android.yml

**Comment by LucasGGamerM** [comment]
Oh wait, normal users cannot download it yet... Will be fixed soon

**Comment by LucasGGamerM** [comment]
Its now properly up here: https://nightly.link/LucasGGamerM/moshidon/workflows/android/master/moshidon-nightly.zip
