### ISSUE TITLE
Choosing an account hides the Favorite menu on the profile page

### ISSUE THREAD

**Issue by FineFindus** [LucasGGamerM/moshidon#142]
**Describe the bug**

The favorites menu button disappears when trying to do an action with another account

**To reproduce**

1. Long press on a status action in the hometimeline, to do it with another account
2. Cancel it by clicking outside the dialog
3. Go to the profile page
4. Notice that the favorite menu is no longer visible

**Screenshots and screen recordings**

![image](https://user-images.githubusercontent.com/63370021/228824967-7319fb4f-72c2-4d67-b6a8-3425b490aea4.png)

**Version**

Moshidon version: v1.2.0+fork.99

**Comment by LucasGGamerM** [comment]
I cannot reproduce this bug on Google pixel running aosp. Maybe an issue with EMUI? I am not sure

**Comment by FineFindus** [comment]
Seems to be fixed in the debug version

**Comment by LucasGGamerM** [comment]
Lovely
