### ISSUE TITLE
Disable scrolling text in title bars not functioning as intended

### ISSUE THREAD

**Issue by DismalShadowX** [LucasGGamerM/moshidon#147]
**Describe the bug**

The option to disable scrolling title bars shows no difference in behavior with it enabled. 

**To reproduce**

1. Go to 'Settings'
2. Click on 'Disable scrolling text in title bars" enabled
3. See Home timelines, still shows text in title bars, no effect with these changes enabled or disabled

**Version**

Moshidon version: [v1.2.0+fork.99] Play Store
Moshidon Nightly version: [v1.2.0+fork.99] Nightly apk

**Comment by LucasGGamerM** [comment]
Can you check if Megalodon has the same issue? This feature is from megalodon, and I didn't touch it at all
