### ISSUE TITLE
Uniform icons for all notifications

### ISSUE THREAD

**Issue by DismalShadowX** [LucasGGamerM/moshidon#148]
**Default enchantment**

Have the option to be disabled by default on clean install.

Not sure why it's enabled by default, presumably for older version of non-Material You devices?

I like seeing shiny icons. 

**Version**

Moshidon version: [v1.2.0+fork.99]
Moshidon Nightly version: [v1.2.0+fork.99]

**Comment by LucasGGamerM** [comment]
It's now as you said. For an explanation, when I merged it over from upstream, I preferred the Mo icon. But i see that many would prefer the custom icons
