### ISSUE TITLE
Minor Notification Banner change

### ISSUE THREAD

**Issue by DismalShadowX** [LucasGGamerM/moshidon#149]
**Describe the solution you'd like**
Boost (Reblog) Add the option or customize them to show in the banner -Currently we have "Reply, Favorite and Bookmark"

**Describe alternatives you've considered**
Customize in setting how you want to see in the notification banner.

**Version**
Moshidon version: [v1.2.0+fork.99] Play Store
Moshidon Nightly version: [v1.2.0+fork.99] Nightly apk

**Comment by LucasGGamerM** [comment]
I think we can make do with swapping bookmark with boosting as an option, because I dont think its productive to have that many settings

**Comment by LucasGGamerM** [comment]
And its now a setting. The default behavior is still bookmark, because that is how @FineFindus thought of.

**Comment by LucasGGamerM** [comment]
You need to receive new notifications for it to change

**Comment by LucasGGamerM** [comment]
Yes. DMs don't allow boosting, that is why it uses the bookmark for those instead
