### ISSUE TITLE
Incorrect Yellow Color Pattern

### ISSUE THREAD

**Issue by DismalShadowX** [LucasGGamerM/moshidon#150]
**Is your feature request related to a problem? Please describe.**
The yellow color pattern looks like soft orange pattern than actual yellow making it harder to read visually.

**Describe the solution you'd like**
Stronger bright yellow

**Version**
Moshidon version: [v1.2.0+fork.99]
Moshidon Nightly version: [v1.2.0+fork.99]

**Comment by LucasGGamerM** [comment]
I got the yellow theme from the material you pallet on my phone, maybe I will try to get something brighter too

**Comment by LucasGGamerM** [comment]
How come I went this long without actively working on this? Its fixed on e55dd0eacaabdaae4d3151d89aafe63268e4827a
