### ISSUE TITLE
Crash in Visual appearance when selecting mode

### ISSUE THREAD

**Issue by DismalShadowX** [LucasGGamerM/moshidon#151]
**Describe the bug**

Crash in Visual appearance when selecting mode between Dark and Light (Nightly Build Only)

**To reproduce**

By default it's 'Automatic'
1. Go to 'Setting'
2. Click on 'Light or Dark'
3. Crashes

**Version**

Moshidon Nightly version: [v1.2.0+fork.99]

If there was a better way than to root or use ADB commands to sent logs.

**Comment by LucasGGamerM** [comment]
It doesnt actually happen in the debug build either, but it does happen in the nightly build downloaded from github. Such a weird issue

**Comment by LucasGGamerM** [comment]
Oh damn you are right, the bug fixed itself somehow

**Comment by LucasGGamerM** [comment]
Fixed with 0c6efac46af6dd29a656b55f17dc7341e945e24a
