### ISSUE TITLE
"Open in App" doesnt work for links from own instance urls

### ISSUE THREAD

**Issue by Mattis142** [LucasGGamerM/moshidon#152]
If youre signed into a certain instance like mastodon.social opening links that use the mastodon.social domain, yet reference another domain wont open in the App.

i.e: http://mastodon.social/@moshidon@floss.social doesnt work while logged into a mastodon.social account

**Comment by LucasGGamerM** [comment]
This is a heisenbug. In case anyone can reliably reproduce this we will reopen
