### ISSUE TITLE
Instance "about" site

### ISSUE THREAD

**Issue by Mattis142** [LucasGGamerM/moshidon#155]
I'd love to see an overview page for instances when you tap the instance part of someoes profile it redirects you to an overview page with relevant information and a button to see the local timeline and also pin it into the timelines menu
![image](https://user-images.githubusercontent.com/40364718/229891797-fa150f13-d7fd-4d1e-9250-11989c41f177.png)

**Comment by FineFindus** [comment]
This can be closed now, as the feature has been introduced in #200.
