### ISSUE TITLE
Improve Material You accents (Light & Dark modes)

### ISSUE THREAD

**Issue by ghost** [LucasGGamerM/moshidon#168]
Just like #150 

Apply a darker or lighter (depends how you define the terms in English xD) accent especially for hyperlinks and hashtags, for the following:

Blue (I think it's fine in Dark mode, hardly visible in Light mode, make it darker) 
Red ( Not bad in Dark mode but very close to pink, looks like brownish or orange in Light mode, not sure it should be darker or lighter)
Green (Doesn't look too bad in Dark mode, hardly visible in Light mode, make it darker)
Brown (Looks like orange in Dark mode maybe lighter, and hardly visible in Light mode, make it darker)

2023/04/15 Nightly

**Comment by LucasGGamerM** [comment]
The brown is supposed to be orange, so I won't touch that. But both blue and red deserve improvements. I believe the rest of the mentioned critiques are very much due.
