### ISSUE TITLE
option to include retooter when replying to retoots

### ISSUE THREAD

**Issue by pwd-github** [LucasGGamerM/moshidon#173]
**Is your feature request related to a problem? Please describe.**

Often I'll see something interesting on my timeline and it will invoke my desire to have a conversation about it. Obviously I'll want to include the person that put it on my timeline, but I have to do this manually every time. 

**Describe the solution you'd like**

A simple option to include the retooter when replying to retoots. 

**Describe alternatives you've considered**
If applicable: a clear and concise description of any alternative solutions or features you've considered.

Automatically including the retooter.

**Additional context**

**Comment by LucasGGamerM** [comment]
Its going to be in the 100th release soon. Its gonna be off by default.

**Comment by pwd-github** [comment]
Thank you for being constantly amazing!
