### ISSUE TITLE
Remote followers load wrong profile picture

### ISSUE THREAD

**Issue by FineFindus** [LucasGGamerM/moshidon#181]
**Describe the bug**

When visiting an instance that changed their default profile picture, a follower without a profile picture will show the instance default picture.

**To reproduce**

1. Visited a profile on an instance, that change their default picture, e.g. https://social.kernel.org/users/torvalds
2. Click on Followers
3. Notice how many followers use the same profile picture
4. Click on a follower, to see that they have the default picture

![Example follower list](https://user-images.githubusercontent.com/63370021/233640878-9151f54b-bfaf-4921-8830-9b9c408a7052.png)

![Example follower profile](https://user-images.githubusercontent.com/63370021/233640875-1b646455-1b92-4f33-af60-e84cb7158241.png)

Additionally, sometimes the follower list shows the wrong profile picture, e.g. it shows the default one, even though the account has one. Could be linked to this issue.

**Comment by LucasGGamerM** [comment]
I think this one is fixed
