### ISSUE TITLE
hide list content from main timeline

### ISSUE THREAD

**Issue by carlnickel** [LucasGGamerM/moshidon#192]
**Is your feature request related to a problem? Please describe.**
I wished my main timeline a bit more cleaned up as there is a lot of traffic from a few specific users.

**Describe the solution you'd like**
Hiding contents from other timelines. I would be great to see content from specific timelines only in these timelines on request - and not in the main timeline. Fedilab supports this feature very will

**Comment by LucasGGamerM** [comment]
Its now a thing on stock mastodon. Moshidon already supports it too!

**Comment by carlnickel** [comment]
Wow, thats so cool. Big improvement. Thank you for your work!

Am 25. September 2023 12:34:09 MESZ schrieb LucasGGamerM ***@***.***>:
