### ISSUE TITLE
Add language selection 

### ISSUE THREAD

**Issue by ronilaukkarinen** [LucasGGamerM/moshidon#2]
On web app it's like this:

![Screenshot_20221209-205419_Chrome](https://user-images.githubusercontent.com/1534150/206775319-7a6cf1ab-f382-4275-804a-0a1e74d9721c.png)

**Comment by LucasGGamerM** [comment]
Sk22 from megalodon is already implementing this. For now I will wait until it becomes ready to then merge it into moshidon :D

**Comment by LucasGGamerM** [comment]
Closed with [version 66](https://github.com/LucasGGamerM/moshidon/releases/tag/1.1.4%2Bfork.66.moshinda)
