### ISSUE TITLE
NonFreeNet

### ISSUE THREAD

**Issue by IzzySoft** [LucasGGamerM/moshidon#206]
I just noticed that Moshidon is marked NonFreeNet in my repo, but it seems I forgot to make a note for the reason. As I see no corresponding library, the most obvious thing coming to mind is that joinmastodon.org is (mandatorily) used for initial signup. Is that the case, or is it also possible to specify a server without it (e.g. manually)? In the latter case, that anti-feature could be dropped.

**Comment by LucasGGamerM** [comment]
Its not *mandatory* per se, but it's what official mastodon uses as a relay for push notifications. I am not sure I can easily change that

**Comment by LucasGGamerM** [comment]
Yes. One can and always will be able to just type your server of choice to login. The only time we connect to joinmastodon.org is when setting up push notifications, which uses joinmastodon.org as a relay for google's FCM to send notifications to Moshidon.

We don't depend on them for anything besides that.

**Comment by FineFindus** [comment]
This is the current Login screen for both [Megalodon](https://github.com/sk22/megalodon) and Moshidon.

![Moshidon Sign in screen](https://github.com/LucasGGamerM/moshidon/assets/63370021/e289a0c9-fcc7-4e76-bbca-76b8aa4bfa66)

Is there anything blocking the Unified Push implementation from https://github.com/sk22/megalodon/issues/108?

**Comment by IzzySoft** [comment]
Thanks @FineFindus! NonFreeNet could thus be removed once the FCM calls are replaced by UP.

**Comment by FineFindus** [comment]
https://github.com/sk22/megalodon/pull/749 has been accepted upstream, it hopefully shouldn't take too long before arriving here. I'm not super familiar with the rules around NonFreeNet, is it enough for FCM to be disabled by default (and can be turned optionally on by the user), or does it have to be permanently disabled in the F-Droid version?
Also, in any case, currently UP is only enabled when the user explicitly decides to do so, we should probably enable it by default in the F-Droid version.

**Comment by IzzySoft** [comment]
> is it enough for FCM to be disabled by default

The library itself is non-free, so F-Droid would reject it. I only know of a single exception of an app using FCM at F-Droid, they wrote the corresponding code themselves and thus got only the NonFreeNet. And I believe you know which one that is, as Moshidon is based on it :wink:

**Comment by FineFindus** [comment]
Sorry, I had a long day, so I'm having a bit of trouble thinking through your sentence. Like the official Mastodon app, we don't use a library for FCM notifications, so we should be in the clear?

Does this apply to notifications in general or only to FCM ones?

**Comment by IzzySoft** [comment]
> Like the official Mastodon app, we don't use a library for FCM notifications, so we should be in the clear?

That's what I meant: Yes, apart from the `NonFreeNet` anti-feature.

> Does this apply to notifications in general or only to FCM ones?

To all bound to non-free services. Should you e.g. switch to @UnifiedPush (for play, you could use a flavor integrating their FCM distributor), `NonFreeNet` could be dropped as one can choose one's own distributor and service, see [Push Clients/Manager](https://android.izzysoft.de/applists/category/named/network_push) in my app listings for some examples.

**Comment by FineFindus** [comment]
Talked with @LucasGGamerM a bit, we agreed that the goal should be to get rid of `NonFreeNet`.  

I've created a new F-Droid flavor, [in which I disabled the code for registering FCM push notifications](https://github.com/FineFindus/moshidon/commit/1ae548c482d884d78679543c29607c91dd389e5b). However, the user still needs to enable UnifiedPush manually in the settings.

Unless, I missed something (in which case, please let me know), I will create a pr on [Megalodon](https://github.com/sk22/megalodon) tomorrow.

**Comment by IzzySoft** [comment]
Does it just "disable" the code, or not even contain it anymore?

**Comment by FineFindus** [comment]
It only disables the code by using an early return (so if the Java compiler would be smarter, it would actually remove the function).

To explain this a bit more, the code for registering for FCM or for UnifiedPush push notifications is nearly identical, we send the server the web endpoint, to which it should post the notifications to. The only difference between registering for FCM is that the `https://app.joinmastodon.org/relay-to/fcm` endpoint is used. This can now no longer be done, due to the early return.

**Comment by IzzySoft** [comment]
Sounds good to me. As the code used here is FOSS, it should be no issue. If you use UP anyway, you could also eliminate the FCM code and instead integrate the FCM distributor for Play builds – but but consider that rather a "note for your interest". Your code is probably compacter :wink: 

So yes, that should be fine. I'd suggest opening an issue (or MR) at fdroiddata to have the AF removed once the new release is outt. We might wish to cross-check then to be sure; not that we wouldn't trust you – but you know, 4 eyes see more and all that :wink:

**Comment by FineFindus** [comment]
> If you use UP anyway, you could also eliminate the FCM code and instead integrate the FCM distributor for Play builds

I don't really want to do that, most of the code is already shared between UP and FCM, and I'm hoping to share even more in the future (e.g. notification decryption). There may also be issues, as UP only relays the message, whereas FCM has additional information attached, which are needed for some features.

> not that we wouldn't trust you

I sometimes don't even trust myself… :)

**Comment by FineFindus** [comment]
The pr for adding the f-droid flavor has been accepted in Megalodon. It will probably take some time to trickle down to this fork, @LucasGGamerM is currently still working on the M3 rewrite, which needs to be merged first.

**Comment by LucasGGamerM** [comment]
This issue shall be closed. The next version (102) should be on fdroid as soon as effectively possible
