### ISSUE TITLE
UX improvement — Change ringing post-notification bell 

### ISSUE THREAD

**Issue by Paol-M** [LucasGGamerM/moshidon#210]
# Problem
It's hard to tell if an account has post notifications enabled.
# Solution
Add small strokes that represent ringing:
Before: 🔔

After: ‘🔔’ (similar to YouTube)

(Yes, I know the icon is filled when post notifications are on. But it would make more sense to fill it and show a “ringing” icon.)

# See screenshots:
## Before
(censored for privacy)
![Mastodon](https://github.com/LucasGGamerM/moshidon/assets/64162487/107e4714-17f0-450a-a273-00a4a84c4a24)
## After
![th-2762138790](https://github.com/LucasGGamerM/moshidon/assets/64162487/599519b3-5608-4a17-97a8-844c0d193c32)

**Comment by Paol-M** [comment]
Also, maybe cross it when notifications aren't enabled. (🔕)

**Comment by LucasGGamerM** [comment]
The censored for privacy got me 🤣

In all seriousness though, your suggestion for changing the icon for enabling post notifications is indeed something I gotta change. But changing the icon for when it isn't enabled to the crossed bell is not something I am quite sold on doing, specially considering the crossed bell "tells" the user that such action is not possible

**Comment by LucasGGamerM** [comment]
I couldn´t find the icon I wanted (which is the one you suggested), but I have come to like this one here 
![image](https://github.com/LucasGGamerM/moshidon/assets/71328265/ad01df89-4fca-42c0-8b54-fc9194c94529)

What do you think?

**Comment by LucasGGamerM** [comment]
I think its quite good, so I will close it for now. Feel free to reopen it! 

It was fixed in commit 57093893229bc5cc45a33e5551999c2d57acb18a
