### ISSUE TITLE
Appears cannot post. Error while saving draft. 

### ISSUE THREAD

**Issue by tonydiep** [LucasGGamerM/moshidon#217]
**Describe the bug**

* Send button not enabled when eplying to toot.
* when going backwards ui asks to save draft
* click save
* error message shows
* 
![Screenshot_20230622-203042](https://github.com/LucasGGamerM/moshidon/assets/705269/7cf659e0-0b07-41fb-99ee-48364fed0752)

**To reproduce**

**Does this happen in the official app?**

No

Does this issue also occur with the respective upstream release?
> No / Yes

> In case it does, please consider filing an [upstream bug report](https://github.com/mastodon/mastodon-android/issues) instead.
> If this bug is seriously impacting your usage or you think I might want to try to fix it for Megalodon, feel free to still create this issue!

**Screenshots and screen recordings**

If applicable, add screenshots (and screen recordings, if possible) to help explain your problem.

**Version**
Moshidonv1.2.3+fork. 101.moshinda (101)

**Crash log**

If you know your way around Android development tools, please consider attaching a crash log, if possible.

**Comment by tonydiep** [comment]
Checked replies using official app.

Turns out Moshidon did post replies but did not change the ui to indicate it had been sent. 

Posting same reply in official app works.

**Comment by LucasGGamerM** [comment]
The send button not being enabled can be due to a lot of things. Have you tried restarting the app to see if it works again?

**Comment by LucasGGamerM** [comment]
It should be fixed now. Feel free to reopen otherwise
