### ISSUE TITLE
More accurate MD3 shades

### ISSUE THREAD

**Issue by TGRush** [LucasGGamerM/moshidon#218]
I've noticed that Moshidon has better/correct shades of MD3 colors in light mode than in dark mode. Currently it seems to use `N2-900` all 'round.

In the future, I'd like the dark mode headers and navigation bar to also be separated by color. E.g by changing the header and navigation bar to use `N2-800` instead

**Comment by LucasGGamerM** [comment]
It should be an easy fix, but remember that mastodon android also shares the same trait in regards to the toolbar as Moshidon, which is why I haven't changed it

**Comment by LucasGGamerM** [comment]
Its fixed ever since the redesign was merged :D
