### ISSUE TITLE
Add option for instances with higher character limit

### ISSUE THREAD

**Issue by ablackcatstail** [LucasGGamerM/moshidon#224]
I run my own instance that has a larger character limit of 5000 characters but I don't see that reflected in Moshidon. Currently, Moshidon shows the default 500 character limit. I really didn't know whether this would be considered a bug or a feature request so I put it here instead so as not to get everyone spun up over something. By the way, this is really a great app from a feature and usability standpoint. It's an overall improvement over the official app.

**Comment by LucasGGamerM** [comment]
It works flawlessly on both my calckey and Akkoma accounts. What server software are you running? This may be an issue with your server side config or something similar

**Comment by ablackcatstail** [comment]
I am running Mastodon v4.1.3, the latest release put out today. I am still limited on the app to only 500 characters despite having configured my mastodon instance to be at 5000.
      
        
        
          On Jul 6 2023, at 11:37 am, LucasGGamerM ***@***.***> wrote:
          
        
        
          
It works flawlessly on both my calckey and Akkoma accounts. What server software are you running? This may be an issue with your server side config or something similar

**Comment by ablackcatstail** [comment]
How very odd! You can close this request out because I discovered that the changes I made to the 3 files to accommodate the increased character length reverted back during my upgrade to v4.1.3. Problem in chair, not in computer. :-)
      
        
        
          On Jul 6 2023, at 11:39 am, Matt Schwartz ***@***.***> wrote:
          
        
        
          I am running Mastodon v4.1.3, the latest release put out today. I am still limited on the app to only 500 characters despite having configured my mastodon instance to be at 5000.
      
        
        
          On Jul 6 2023, at 11:37 am, LucasGGamerM ***@***.***> wrote:
          
        
        
          
It works flawlessly on both my calckey and Akkoma accounts. What server software are you running? This may be an issue with your server side config or something similar

**Comment by LucasGGamerM** [comment]
I am glad to see it was resolved!
