### ISSUE TITLE
Viewing other instances local timeline still shows a (incorrect) reason the toot appears in the timeline

### ISSUE THREAD

**Issue by ZeroEcks** [LucasGGamerM/moshidon#227]
**Describe the bug**

If you add another instances local timeline, it still shows "#hashtag" as the reason a toot is displayed, even though it's not your timeline.

**To reproduce**

1. Add another instances timeline
2. Follow a hashtag
3. Find a post on the other instances timeline with the hashtag
4. It highlights this tag above the post.

**Does this happen in the official app?**

Does this issue also occur with the respective upstream release?

- No, this feature does not appear on the official app

**Screenshots and screen recordings**

![Screenshot_20230707_175610_Moshidon.png](https://github.com/LucasGGamerM/moshidon/assets/1106524/e99136e9-9a90-40e3-bccb-b22378d06116)

**Version**

Moshidon version: v1.2.3+fork.101.moshida (101)

**Comment by LucasGGamerM** [comment]
I believe this is intended behavior. The hashtag on top of the post is just an indictive that such post contains a hashtag you follow

**Comment by ZeroEcks** [comment]
Fair enough, I think either interpretation is fine. Feel free to close.
