### ISSUE TITLE
What's the difference between Moshidon and Megalodon?

### ISSUE THREAD

**Issue by moshpirit** [LucasGGamerM/moshidon#230]
Moshidon is a fork of Megalodon, but what are the differences? Does Moshidon have more features?

**Comment by FineFindus** [comment]
Yes. The [README](https://github.com/LucasGGamerM/moshidon#detailed-changes) lists a few features, but most of them are also shared with Megalodon. The [FAQ](https://github.com/LucasGGamerM/moshidon/blob/master/FAQ.md) also tries to answer this question in a shorter way.

**Comment by moshpirit** [comment]
I see, thanks a lot!!
