### ISSUE TITLE
Support for Glitch-Soc and Glitch-Soc style reactions

### ISSUE THREAD

**Issue by ObsoletePixel** [LucasGGamerM/moshidon#238]
Glitch-soc is a popular fork of mastodon and being able to have native interaction with glitch-soc instances and features via this app would help interoperability with more mastodon instances

Adding support for reactions natively to the app, but also adding support for displaying markdown or HTML-formatted posts would make the app even more useful to more users.

As far as I'm aware, very few mastodon clients for android support these features, and moshidon is best-in-class for its usability and UI, which would then give it another defining trait over the official Mastodon app or other similar forks/projects

**Comment by Tyketc** [comment]
What is meant by "Glitch-Soc style reactions"? The support for reactions is still in the draft stage, specifically if you are referring to "emoji reactions".

Furthermore, moshidon `v1.2.3+fork.101.moshinda` has already included the ability to modify post formats. The display of markdown and HTML-formatted posts was supported even before this update.

**Comment by LucasGGamerM** [comment]
@sk22 is working on the emoji reactions, its coming in the next stable release

**Comment by sk22** [comment]
> adding support for displaying markdown or HTML-formatted posts would make the app even more useful to more users.

huh? that's been in megalodon and moshidon for a long time

**Comment by LucasGGamerM** [comment]
> > adding support for displaying markdown or HTML-formatted posts would make the app even more useful to more users.
> 
> huh? that's been in megalodon and moshidon for a long time

I got confused there for a moment. I thought he meant the Emoji reactions to statuses
