### ISSUE TITLE
Add rearrange image ability

### ISSUE THREAD

**Issue by Mannivu** [LucasGGamerM/moshidon#240]
**Is your feature request related to a problem? Please describe.**
When uploading multiple image, the app doesn't follow the order the user has selected them (and sometimes that order is important)

**Describe the solution you'd like**
I've seen that the official app has a drag-and-drop method to rearrange the pictures added to a toot.

**Comment by LucasGGamerM** [comment]
Ever since the M3 redesign this has been posdible

**Comment by Mannivu** [comment]
I'm sure about this, but I still can't rearrange the pictures after adding them to a post

**Comment by LucasGGamerM** [comment]
You gotta long hold the images, and then drag them to the side to rearrange them

**Comment by Mannivu** [comment]
In Moshidon this doesn't work

https://github.com/LucasGGamerM/moshidon/assets/42747216/7f92c25e-57fe-4839-8566-b78000c5207f

**Comment by Mannivu** [comment]
Updated to the latest release and now it works
