### ISSUE TITLE
Crash on poll edit

### ISSUE THREAD

**Issue by LucasGGamerM** [LucasGGamerM/moshidon#243]

**Comment by IAGOnGithub** [comment]
Also occurs when deleting and redrafting polls. The poll gets deleted but Moshidon crashes when trying to edit it.
IIRC, it also occurs when editing a draft poll.

**Comment by CivilizedGuide** [comment]
Same here when trying to edit a draft with a poll

**Comment by LucasGGamerM** [comment]
Thank you for reminding me
