### ISSUE TITLE
Remove emojis from display names

### ISSUE THREAD

**Issue by AtlasC0R3** [LucasGGamerM/moshidon#248]
**Describe the solution you'd like**
[Pinafore](https://pinafore.social), a [now unmaintained](https://nolanlawson.com/2023/01/09/retiring-pinafore/) Mastodon/Pleroma client has an option to remove any and all emojis from display names, for accessibility (and wellbeing) reasons. I think this would be a fantastic, if purely cosmetic or complementary, option to have in this client.

[I have found the JS file that removes the emoji](https://github.com/nolanlawson/pinafore/blob/master/src/routes/_utils/removeEmoji.js), but I'll be honest and say I don't quite understand how it works; I won't promise anything but I'll try to see how it functions later, if needed.

**Describe alternatives you've considered**
...er, taking it into stride and ignoring it, but I feel it only adds noise/clutter to the screen, plus ignoring things is difficult for some people.

**Comment by FineFindus** [comment]
I'm a bit confused, how would not showing emojis in display names improve wellbeing?

**Comment by AtlasC0R3** [comment]
Less distractions, flashy colors. Some people just don't want to have to see or think about it.

**Comment by LucasGGamerM** [comment]
There is already a setting for that under display. Hopefully that suits your needs

**Comment by AtlasC0R3** [comment]
> There is already a setting for that under display. Hopefully that suits your needs 

It doesn't fully replace emojis, only prevents custom ones from displaying (and even then it still shows the ID). I was expecting one that removes normal emojis as well as completely removing the \:emoji_id\: leftover.

![Screenshot_20230830-153851.png](https://github.com/LucasGGamerM/moshidon/assets/39468657/22d23095-0d46-4b5d-980a-a2d887b0ba3d)
![Screenshot_20230830-153910.png](https://github.com/LucasGGamerM/moshidon/assets/39468657/e52c08be-e74a-4816-8010-bd37c9083063)

**Comment by AtlasC0R3** [comment]
Looking into Pinafore's code, for custom emojis it uses a list of emojis that it knows will display in the name (for example we have "Username :emoji_1:", the client knows `emoji_1` is a custom emoji with an image to display) and simply replaces them via their name all to nothing (so replace ":emoji_1:" to "", so on with every other emoji that there may be).

As for normal emojis, [Pinafore handles those here.](https://github.com/nolanlawson/pinafore/blob/master/src/routes/_utils/replaceEmoji.js#L7) It uses a regex to filter strings to anything that _isn't_ an emoji, as indicated by the `NON_EMOJI_REGEX` variable whose value is `/^(?:[0-9#*]|™|®|©|\ufe0f)+$/`.

**Comment by LucasGGamerM** [comment]
Damn, the regex is gold. Thank you
