### ISSUE TITLE
FEATURE: Most used languages at the top on language selector 

### ISSUE THREAD

**Issue by maikelthedev** [LucasGGamerM/moshidon#251]
This is a mess inherited from the official app. 
![image](https://github.com/LucasGGamerM/moshidon/assets/29461493/8d9fc5ff-7b44-46c1-b141-126d2182474a)

Expected behaviour:

If I tag most of my stuff in either English or Spanish, the app **should** remember it and put those two languages at the top. Having to scroll to find my mother tongue adds a lot of friction and is poor UX.

**Comment by LucasGGamerM** [comment]
It's already fixed in the nightly build. You can try it here: https://github.com/LucasGGamerM/moshidon-nightly/releases/latest/download/moshidon-nightly.apk

**Comment by maikelthedev** [comment]
> It's already fixed in the nightly build. You can try it here: https://github.com/LucasGGamerM/moshidon-nightly/releases/latest/download/moshidon-nightly.apk 

I just tried. It isn't. Still only English at the top after two posts in Spanish ![Screenshot_2023-09-03-14-08-10-412_org.joinmastodon.android.moshinda.nightly.jpg](https://github.com/LucasGGamerM/moshidon/assets/29461493/b50073b8-ee12-4ca8-922c-9c30221a9ad1)
