### ISSUE TITLE
Getting "ValidationError: Text can't be blank" with text written on post

### ISSUE THREAD

**Issue by JuanjoSalvador** [LucasGGamerM/moshidon#257]
**Describe the bug**

Trying to send a post, sometimes with no reasson, validation can fail and not allowing you sending the post. Message that shows is "ValidationError: Text can't be blank", but there is text written on it.

My first impression is the bug comes from a trailing whitespace, but tested with and without it and still works. Is not blocking since you can send the post if you try again.

**To reproduce**

1. Go to 'New post'
2. Write a post with and without trailing whitespace
3. Click on 'Send.'

**Does this happen in the official app?**

Does this issue also occur with the respective upstream release?
* [ ] Yes
* [x] No

> In case it does, please consider filing an [upstream bug report](https://github.com/mastodon/mastodon-android/issues) instead.
> If this bug is seriously impacting your usage or you think I might want to try to fix it for Megalodon, feel free to still create this issue!

**Screenshots and screen recordings**

If applicable, add screenshots (and screen recordings, if possible) to help explain your problem.

![image](https://github.com/LucasGGamerM/moshidon/assets/5058655/45849a83-5fae-4148-ac09-cba45cd92e3b)

**Version**

Moshidon version: `1.2.3+fork101.moshinda-play (101)`

**Crash log**

If you know your way around Android development tools, please consider attaching a crash log, if possible.

**Comment by LucasGGamerM** [comment]
It's a really weird bug for sure. It seems like an instance issue. In any case. Can you please try the Nightly version of Moshidon?

**Comment by bama35453** [comment]
My educated guess is that this is related to the Mastodon software on your respective instance.
I'm on mastodon.social. Since it has been updated to v4.2.0-nightly.2023-09-13 the error disappeared from what I can tell so far.

**Comment by LucasGGamerM** [comment]
Then this issue shall be closed

**Comment by JuanjoSalvador** [comment]
I'm still getting the same error but not with every post. Anyway if it seems like an instance problem, maybe we should try with another instance.
