### ISSUE TITLE
Change toot to post in settings

### ISSUE THREAD

**Issue by MKCOOL142** [LucasGGamerM/moshidon#26]
The Setting "Disable Toot dividers" should be renamed to "Disable Post Dividers" as officially posts are not called toots anymore

**Comment by LucasGGamerM** [comment]
Okay, thanks for the heads up! Will change that up tomorrow

**Comment by LucasGGamerM** [comment]
Fixed in c8d160fc3520bf5e10319dc272726fc284c1ec03
