### ISSUE TITLE
Crash on 2023-10-01 nightly

### ISSUE THREAD

**Issue by Draky50110** [LucasGGamerM/moshidon#269]
Hello.

Trying 2023-10-01 nightly, it crashes swiping my timeline.

Pasted the error : https://pastebin.com/kjfcqfYx

It always crash when it tries to display this post : https://mastodon.social/@justinmponcet@sciences.re/111160921926949764 (retooted from someone else I'm following).

Not sure if linked to "Load more toots" as it didn't display.

**Comment by LucasGGamerM** [comment]
Weird. I cannot reproduce the crash.

**Comment by Draky50110** [comment]
I close as it was fixed (hashtag problem) on 2023-10-02 nightly.
