### ISSUE TITLE
Search shortcut 

### ISSUE THREAD

**Issue by MKCOOL142** [LucasGGamerM/moshidon#27]
I would love to see this small quality of life feature:
Long pressing the search button on the navigation bar sould automatically
1. Switch to the Search/Explore Tab
2. Open the Keyboard

Additionally when you're already on the search/explore tab a simple tap (not exclusively long press) should ALSO open the Keyboard

**Comment by LucasGGamerM** [comment]
For sure! I will look at it tomorrow

**Comment by MKCOOL142** [comment]
Dw you can look at them tomorrow, I just wanted to write them down here instead of spamming you on masto so that they're more centralized 😅

**Comment by LucasGGamerM** [comment]
Thank you!

**Comment by LucasGGamerM** [comment]
Its fixed with ee0737c9c76c1c4c6646238186b5591c779767de
