### ISSUE TITLE
export and import a back up file

### ISSUE THREAD

**Issue by travisfw** [LucasGGamerM/moshidon#273]
## problem
I want to try the Moshidon build from github, which is ahead of the one on F-Droid, but I cannot back up my settings, so I would have to uninstall, reauthenticate with all my accounts, change the settings to my previous defaults (if I can even remember exactly what they were), and if anything goes wrong (like if future updates require me to remember or check) then I would have to do it again to go back to F-Droid or Play.

## solution
Enable backing up the authentications and configurations so that I can uninstall the app without risking spending considerable more time in case of later reinstall.

## alternatives
Are there any?

## Additional context
I actively use four accounts

**Comment by ddkkii** [comment]
Would love this, as well, since I use the app on a tablet and phone and having to recreate the various lists and settings that I prefer is a pain. Plus I'll be upgrading phones soon and this would be a life saver for that.
