### ISSUE TITLE
F-Droid.org

### ISSUE THREAD

**Issue by LucasGGamerM** [LucasGGamerM/moshidon#275]
Initial motion has been started at: https://gitlab.com/fdroid/rfp/-/issues/2555

**Comment by LucasGGamerM** [comment]
The PR has been opened at https://gitlab.com/fdroid/fdroiddata/-/merge_requests/13866

**Comment by LucasGGamerM** [comment]
The PR has been merged! We should see Moshidon on the fdroid store in the following days

**Comment by IzzySoft** [comment]
Hi @LucasGGamerM, with your app now listed at F-Droid, do you want me to keep it in my repo too (I see your Readme still carries my badge, but not F-Droid's)? As you've established reproducible builds there, that would be possible without "side effects" (like confusion due to different signatures).

**Comment by IzzySoft** [comment]
@LucasGGamerM seems you've missed my ping. What's your stance? If there's none, I'd go ahead removing it from my repo (which would be the standard procedure) – but then the link from your Readme will produce a 404, causing a little confusion :wink:

**Comment by LucasGGamerM** [comment]
The previous ping went off my radar, I am sorry :( 

I thing keeping it there won't be that big of a deal, so yes, I think keeping Moshidon on your repo too would be awesome!

Thank you :D

**Comment by IzzySoft** [comment]
As you've established reproducible builds I agree this can be done. OK, as you requested it, I gladly comply and mark it to be kept, thanks!
