### ISSUE TITLE
Media Card Display Options

### ISSUE THREAD

**Issue by ChrisPirillo** [LucasGGamerM/moshidon#279]
**Is your feature request related to a problem? Please describe.**
Well, it's more a preference. The media card [external link's photo, destination headline, description] embeds in the timeline currently are all-or-nothing, and they bleed completely to the edge - or, at times, there are no images so we just end up with a huge blank space that isn't collapsed. I believe you call this "media preview?"

**Describe the solution you'd like**
Far more granular layout options. I would prefer the Media Cards to look and work much more closely to that of Mastodon's advanced web interface, perhaps. Where they don't bleed to the edge, are encapsulated in a rounded-corner square (or at least indented). If there is no external image, then that area should be collapsed and not even visible as blank space. And, for that matter, allowing *all* post text to be indented to reduce visual clutter and increase readability when scrolling. 

**Describe alternatives you've considered**
Turning off Media Cards, which isn't practical. Waiting for more options. Switching back to Tusky (which I don't want to do, as I think Moshidon's design is a lot more modern). 

**Additional context**
Far more granular layout options, please - for Media Cards or how timelines are formatted in general. 

![Screenshot_20231007_172546_Moshidon](https://github.com/LucasGGamerM/moshidon/assets/59216/b3ba9f27-879a-4b76-9948-ed5006c021e1)

**Comment by Xen4n** [comment]
I also have problem with empty space media preview (or unloaded previews for links)
