### ISSUE TITLE
Favourite counts showing different numbers

### ISSUE THREAD

**Issue by astro-ray** [LucasGGamerM/moshidon#281]
**Describe the bug**

In timeline the favourite count is different from when the post is selected

My account is on mastodon.social and this discrepancy is on fediscience.org

**To reproduce**
I am not quite sure how to reproduce it

**Does this happen in the official app?**

This is happening with a feature that is not available on the official app

Does this issue also occur with the respective upstream release?
> No

> In case it does, please consider filing an [upstream bug report]
(https://github.com/mastodon/mastodon-android/issues) instead.
> If this bug is seriously impacting your usage or you think I might want to try to fix it for Megalodon, feel free to still create this issue!

**Screenshots and screen recordings**

![Screenshot_20231015_191909_Moshidon](https://github.com/LucasGGamerM/moshidon/assets/69363775/a285e4b6-d566-4c14-a250-75c8d5afc724)
![Screenshot_20231015_191849_Moshidon](https://github.com/LucasGGamerM/moshidon/assets/69363775/825a1f73-ba4c-412c-87f3-b2842c674459)

If applicable, add screenshots (and screen recordings, if possible) to help explain your problem.

**Version**

Moshidon version: 2.1.4+fork.102.moshinda

**Crash log**

If you know your way around Android development tools, please consider attaching a crash log, if possible.

**Comment by LucasGGamerM** [comment]
This is a bug with federation, and there isn't much that I can do to fix it.

Its a pain :(
