### ISSUE TITLE
Can't install update

### ISSUE THREAD

**Issue by itsFurty** [LucasGGamerM/moshidon#285]
After downloading Moshidon 2.1.4+fork. 102 update from the settings panel I am unable to Install it. Clicking on the Install button has no effect. 

Running the official app from the Google Play store. 

Moshidon version: v1.2.3+fork.101.moshinda (101)

**Comment by LucasGGamerM** [comment]
I am not sure understand what is happening here. But I'm sure the play smrelease does not have an auto updater

**Comment by itsFurty** [comment]
Here is a screengrab of my settings panel. 

![Screenshot_20231021_192920_Moshidon](https://github.com/LucasGGamerM/moshidon/assets/57392195/525961c3-6e0d-4e61-ba23-cd83cbeb78f4)

**Comment by LucasGGamerM** [comment]
Weird... I am sorry for any inconveniences, but manually downloading the update should fix it

**Comment by itsFurty** [comment]
Worked perfectly. In the future I'll just download the latest release from here and manually update. Appreciate your quick reply and help.

**Comment by LucasGGamerM** [comment]
You are welcome! Feel free to ask any further questions
