### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by samtrek** [LucasGGamerM/moshidon#29]
**Is your feature request related to a problem? Please describe.**
The app only post a single notification clearing the other notifications while doing so.
**Describe the solution you'd like**
The app should be able to accomodate multiple notifications coming from same or multiple accounts

**Describe alternatives you've considered**
If applicable: a clear and concise description of any alternative solutions or features you've considered.
None but the other app that I have used have used `ntfy` as their notification server and manager, I dont know if this will help.
**Additional context**
The tusky app uses `ntfy` as its notification manager it might be worth checking out.

**Comment by cjseaslug** [comment]
Chiming in to mention that I dont get notifs, I assume it's related to not having Google Play services. I understand if changing the notif platform would be too many moving parts for a fork, but would be a killer feature :)

**Comment by LucasGGamerM** [comment]
I also do not have google play services, but I do have microG. Its planned to add a way to at least have notifications on degoogled devices

**Comment by LucasGGamerM** [comment]
Its allowing multiple notifications by default on commit 67338b6c8567c79146128084ac34077eb357b5c0

**Comment by LucasGGamerM** [comment]
What shall I name the setting?

**Comment by samtrek** [comment]
`enable multiple notifications`? with a little bit of explanation about what it does under the option

**Comment by LucasGGamerM** [comment]
After asking that on Mastodon, "Keep only latest notification" sounded the clearest for me, so I have chosen that. I am still in the process of finding a better icon though

**Comment by LucasGGamerM** [comment]
Its basically fixed. The notifications without google play services is still not working though

**Comment by LucasGGamerM** [comment]
Needed to reopen this one, as the notifications are not yet handled properly. Ie: If the user clicks a notifications, the one that will open is the latest one, and not the one the user clicked. This still needs fixing

**Comment by LucasGGamerM** [comment]
Its now fixed with 20768182209001d9a7bd6a3d1f3be5548395f5a3
