### ISSUE TITLE
Crash when starting a search with # on an Akkoma server

### ISSUE THREAD

**Issue by ymollard** [LucasGGamerM/moshidon#291]
**Describe the bug**

The app crashes when starting a search with `#` on an Akkoma server.
The crash does not occur if the searched string does not start with a `#`

**To reproduce**

1. Create an account on an Akkoma server, e.g. I used https://bdx.town
2. Connect to this account on Moshidon
3. Open the search field and type only the character # 
4. The app crashes after a few millisec, probably when the server responds

**Does this happen in the official app?**

This bug does not affect Megalodon, but I don't know for the Mastodon app.

**Version**

Moshidon version: 2.1.4+fork.102.moshinda (102)

**Comment by LucasGGamerM** [comment]
This has been fixed a while ago. See if it happens on the Nightly version at https://github.com/LucasGGamerM/moshidon-nightly/releases/latest/download/moshidon-nightly.apk
