### ISSUE TITLE
Add 'Mute This Conversation'

### ISSUE THREAD

**Issue by NonITExpert** [LucasGGamerM/moshidon#298]
Please add option to mute a specific post/conversation, rather than create a filter which is more broad. Sometimes muting a specific convo is all you need.

**Comment by LucasGGamerM** [comment]
This has been implemented in the current unstable 'Nightly' builds, and will be seen on a stable release soon

**Comment by NonITExpert** [comment]
Thank you for responding. The problem is I am using Nightly now, installed version dated 11-8-23. In Nightly, when I open a conversation and click the 3 dots I see options to Follow, Mute, Block or Report the user, not the conversation. And that's my point. My request is for an option to block a specific **_post/conversation_**. I don't see that in Nightly. Can you let me know where that is?

**Comment by LucasGGamerM** [comment]
You gotta be mentioned in the post for the mute option to show up
