### ISSUE TITLE
Lists as tabs to main view

### ISSUE THREAD

**Issue by ronilaukkarinen** [LucasGGamerM/moshidon#3]
Right now to access lists you need to click search icon, scroll all the way to the end, tap "Lists", then tap list name.

Could you add lists as tabs to home view on top?

**Comment by LucasGGamerM** [comment]
I will see what I can better do with the lists. For now though, idk where to better put it

**Comment by sk22** [comment]
i thought about maybe having a list/home button (with a dropdown where you can select the desired timeline) on the top left on the home view, but i haven't had the time to try that yet

**Comment by LucasGGamerM** [comment]
That seems a lot more reasonable than my current try at doing this. But still, the thing that I am stuck on is getting a list of lists. I think I should look over the code a bit more to try and find out how exactly you get a list of lists.

**Comment by sk22** [comment]
well i used this PR as a basis: https://github.com/mastodon/mastodon-android/pull/286

**Comment by ronilaukkarinen** [comment]
> I will see what I can better do with the lists. For now though, idk where to better put it

Sorry for using the bird site as example, but the tabs on top was actually what I was looking for:

![image](https://user-images.githubusercontent.com/1534150/206895983-3dde6ff3-eee1-445e-92d5-a0fd2f0a23ec.png)

**Comment by LucasGGamerM** [comment]
ok, so I have thought about if for a while. And there will be a separate lists button on the tabbar (bottom menu), where there will be your lists. And they will be in tabs. Thank you for your screenshot!

**Comment by LucasGGamerM** [comment]
Ok, so for now I have decided to put them in the third place in the tabs view. Its better than last at least. I know it isn't the exact thing you want though. I will revisit once I get the UI ready for deleting, editing and creating new lists. 
![Screenshot_20221211-201041](https://user-images.githubusercontent.com/71328265/206934441-6c054bc7-dc2c-437c-a218-58396809cfb6.png)
