### ISSUE TITLE
Error: java.lang.NumberFormatException

### ISSUE THREAD

**Issue by AncientCatz** [LucasGGamerM/moshidon#307]
**Describe the bug**

Hey there! 👋 So, I ran into a little hiccup with the app. It seems like when pulling data from the API of the Akkoma instance at [ak.vern.cc](https://ak.vern.cc), we're getting a massive number that's too large for `int` to handle. This ends up throwing a `java.lang.NumberFormatException` error.

Interestingly, other Akkoma instances don't cause this issue because their data fits into the `int` range. It looks like Moshidon might be struggling with handling such large data.

Any thoughts on how we can gracefully handle these larger numbers, maybe switch to `long` or consider using `BigInteger`?

**Does this happen in the official app?**

Does this issue also occur with the respective upstream release?
> No

**Screenshots and screen recordings**

<details><summary>Screenshot</summary>

![Screenshot_2023-11-25-23-52-10-763_org joinmastodon android moshinda](https://github.com/LucasGGamerM/moshidon/assets/69200720/b0012f4d-5dfe-46b9-998b-e78b5509bdfe)

</details>

<details><summary>Screen recording</summary>

https://github.com/LucasGGamerM/moshidon/assets/69200720/4f38a1b3-8c00-4236-98f7-26ce64d1e2f0

</details>

**Version**

Moshidon version: 2.1.4+fork.102.moshinda

**Comment by LucasGGamerM** [comment]
This is wtf levels of high integer

How can this even happen? 

I will see what I can do

**Comment by massahud** [comment]
looks like an unsigned long

**Comment by LucasGGamerM** [comment]
Looks like this also happens with clubcyberia.co

It might be good to actually fix this for once, as it doesn't look like a thing that instance admins would bother with

**Comment by LucasGGamerM** [comment]
Fixed with e0ff1f672500d184c0eedd0f2ab6fc79cc185ca7 

:D
