### ISSUE TITLE
Share button is misaligned 

### ISSUE THREAD

**Issue by MKCOOL142** [LucasGGamerM/moshidon#31]
The share profile button in moshidon is misaligned, this isn't the case in megalodon or Mastodon tho
![Screenshot_20230103-224225_Moshidon](https://user-images.githubusercontent.com/40364718/210446525-90aaa426-4533-49b1-ad26-a7b948cad8c0.png)
![Screenshot_20230103-224222](https://user-images.githubusercontent.com/40364718/210446534-bcf25b1c-235e-4182-8da8-c794eeb1b06e.png)

**Comment by LucasGGamerM** [comment]
Didn't notice that one there. Fixing it soon

**Comment by LucasGGamerM** [comment]
I fixed it in a commit a little while ago
