### ISSUE TITLE
Notifications > Everything tab appears empty

### ISSUE THREAD

**Issue by joenepraat** [LucasGGamerM/moshidon#314]
**Describe the bug**

When I go to the notifications tab, only the text "This list is empty" appear under Everything (see screenshot). When I swipe down (the refresh gesture) the notifications appear. Another way to do let them appear is to click on the filter icon and click Save (all boxes are checked). The Mentions tab works like it should.

After I close Moshidon and re-open it, the notifications tab appear empty again. Even when the number of new notifications are on the 🔔 icon, there is still nothing below the Notifications > Everything tab.

**To reproduce**

See above.

**Does this happen in the official app?**

Does this issue also occur with the respective upstream release?

No (also not in Megalodon afaik)

**Screenshots and screen recordings**

[text continues below screenshot]
![Screenshot_2023-12-10-21-22-53-19_0029afb8f6970db29ce334100be72bad](https://github.com/LucasGGamerM/moshidon/assets/41594439/787997d6-69c5-4c63-accb-eb7bc19f9f3a)

**Version**

Moshidon version: v2.1.4+fork.103.moshinda (103)

**Crash log**

Not available, because it's no crash.

**Comment by LucasGGamerM** [comment]
Can you try reloading it? If that doesn't work, then we need more info to debug it

**Comment by joenepraat** [comment]
> Can you try reloading it? If that doesn't work, then we need more info to debug it. Stuff like your instance

What you mean with reloading it? If I refresh that page, they appear. But not after I click on the notifications (🔔) icon. The notifications stay when the app is open, but when I close it (or open another app), the notifications tab/page is empty again.

**Comment by joenepraat** [comment]
BTW: It happens with all my accounts (3) and it started right after I re-installed Moshidon. I suspect it has something to do with the filter you added.

**Comment by joenepraat** [comment]
@LucasGGamerM This explains it probably better.

https://github.com/LucasGGamerM/moshidon/assets/41594439/c286f2a1-f1f2-4c8e-85f9-2a19c7538c7e

**Comment by LucasGGamerM** [comment]
Sounds like a cache issue. Can you try clearing the app cache from the android settings?

**Comment by joenepraat** [comment]
> Sounds like a cache issue. Can you try clearing the app cache from the android settings? 

No, that is not it. I emptied the Android cache already, but tried it again to be sure. Remember that it started right after I installed Moshidon, and that this never happened in Megalodon and the official app.

**Comment by joenepraat** [comment]
I tested some more and it seemed that it only happens on todon.nl. I'm going to test further tomorrow.

**Comment by joenepraat** [comment]
I reinstalled Moshidon and it works fine. I'm astonished! 

Sorry for any inconvenience. I really don't know what happened.
