### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [LucasGGamerM/moshidon#315]
ref: https://monitor.f-droid.org/builds/log/org.joinmastodon.android.moshinda/103#site-footer

diff log:  [mosh103.log](https://github.com/LucasGGamerM/moshidon/files/13635262/mosh103.log)

Looks like you built your APK from another commit maybe

/LE: fyi  https://gitlab.com/fdroid/fdroiddata/-/commit/fc430521b58668e809d3b1c30f0e416f1bd334e6

**Comment by LucasGGamerM** [comment]
I will see what could be happening here, but it seems like I was using a self built version of the appkit libs, which may or may not have caused issues with the diff. I will try rebuilding it with the maven central version to see if it changes. I will ping you back once it done. 

Thank you for bringing this to my attention!

**Comment by LucasGGamerM** [comment]
I have rebuilt it, and the hash between the newly built binary and the one in the release is equal, which is strange. I will try cleaning up somethings to see if anything changes

**Comment by LucasGGamerM** [comment]
Can you please try retriggering the build just in case @licaon-kter ?

**Comment by licaon-kter** [comment]
Wait, you were building a different source code that used libs from elsewhere?

Also, why bother triggering now if your new apk is the same as the old one?

**Comment by licaon-kter** [comment]
> No, it's the same source

The how come the same source will pull Appkit from maven for me but will use it from elsewhere for you?

> I requested a new trigger because sometimes stuff goes wrong with GitHub downloading a broken APK. That happened sometimes with me.

The APK is still 4 days old...  and it's sha256 hashsum is the same with the one I diffed against.

> I don't know where else to look for. 

If you build locally the run `gradle clean` and whatever else is needed, and maybe build from command line instead.

**Comment by LucasGGamerM** [comment]
I cleaned the gradle cache and made android studio use the jdk from the Pop!_OS (ubuntu based) repos, and that seemed to change things. The hash is now different! And hopefully it should work now

**Comment by LucasGGamerM** [comment]
I have updated the apk too, so the build should work now. Can you try it again?

**Comment by licaon-kter** [comment]
new difflog: 
[moshi103.log](https://github.com/LucasGGamerM/moshidon/files/13686786/moshi103.log)

**Comment by LucasGGamerM** [comment]
> new difflog: [moshi103.log](https://github.com/LucasGGamerM/moshidon/files/13686786/moshi103.log)

Did it still fail?

**Comment by licaon-kter** [comment]
No, it builds... but it's not reproducible

**Comment by LucasGGamerM** [comment]
Imma try and redo it via the command line. I will keep you posted 

We are gonna figure this out

**Comment by LucasGGamerM** [comment]
I have just updated the apk again. I have built it from the command line and it should work now. It has a new hash and hopefully it works.

cc: @licaon-kter

**Comment by LucasGGamerM** [comment]
> No, it builds... but it's not reproducible

It should be reproducible now

**Comment by licaon-kter** [comment]
Nope, same diff log :(

**Comment by LucasGGamerM** [comment]
Goddamnit. I will setup another environment here somewhere to make this thing work

**Comment by licaon-kter** [comment]
I'm rebuilding locally just to make sure...

**Comment by licaon-kter** [comment]
nope, no joy :(

**Comment by LucasGGamerM** [comment]
I have updated the APK once more. I have redownloaded Android Studio as a flatpak (I was using flatpaked android studio when we set up reproducible builds) and it should work now. Hopefully, I hope

**Comment by LucasGGamerM** [comment]
Hey I just built it on another machine and the hash is different from any others I have had. Hopefully this time it works

**Comment by LucasGGamerM** [comment]
> Every time somebody says _"just built it on another machine and the hash is different from any others I have had"_ I get a bit more angry :) :) this does not sound like a good ending :)) :((

Well, I am truly sorry. It should have worked from the start. I too am quite angry at how this came to be. I am still trying to find the culprit in my main rig.

**Comment by licaon-kter** [comment]
No, it's okay, we keep trying, just musing on the meaning of it :smile: 

testing now, brb

**Comment by licaon-kter** [comment]
@LucasGGamerM better https://gitlab.com/fdroid/fdroiddata/-/commit/a97a8cac258e6c3d68f32c508b923419e6f4159d

now, _what did you do_? :smile:

**Comment by LucasGGamerM** [comment]
I just dug up my old laptop and compiled there. IDK what or how stuff go wrong in my main rig

**Comment by linsui** [comment]
It's not a different jdk?

**Comment by LucasGGamerM** [comment]
Nope, It's actually almost a carbon copy of my main rig, same everything. But somehow it compiled reproducibly. I guess I shall now compile the Fdroid releases there from now on :D

**Comment by licaon-kter** [comment]
you've added suffixes for versionName: https://github.com/LucasGGamerM/moshidon/commit/711c70af2f061c3002c88f7d37397e64180bb729 and now APK paths can't be matched: https://gitlab.com/fdroid/fdroiddata/-/jobs/7465196373#L543

either drop the suffix or tag as `2.3.0+fork.106.moshinda-fdroid`

**Comment by LucasGGamerM** [comment]
Hmmmm... Is there anything else we can do that avoids pushing out a new release?

**Comment by licaon-kter** [comment]
Autoupdate uses the "previous version block" to generate a "new build block", so this needs to be fixed for the version we'd use now but also be already fine for the next one too.

**Comment by LucasGGamerM** [comment]
So I'm not sure I understand. Should I create a new release and change the version name again or should I leave it as is?

**Comment by licaon-kter** [comment]
What did you decide to do?

**Comment by LucasGGamerM** [comment]
> What did you decide to do? You'll drop suffix?

I have decided to keep it, as it helps to distinguish the flavors when debugging flavor specific issues.

**Comment by licaon-kter** [comment]
ok, so all your tags will be name `2.3.0+fork.106.moshinda-fdroid` from now ok? or you want to drop autoupdates?

**Comment by LucasGGamerM** [comment]
> ok, so all your tags will be name `2.x.x+fork.yyy.moshinda-fdroid` from now? or you want to drop autoupdates?

They will be just like that for the foreseeable future

**Comment by licaon-kter** [comment]
Ok, so I'll disable autoupdates for the foreseeable future

Feel free to come and add new versions via merge requests

**Comment by LucasGGamerM** [comment]
> Ok, so I'll disable autoupdates for the foreseeable future
> 
> Feel free to come and add new versions via merge requests

Hmmm, I was under the perspective we could change the version name while maintaining the auto updates :( 

Is there anything else we can do?/

**Comment by licaon-kter** [comment]
Then maybe we are lost in translation? :)

**Comment by licaon-kter** [comment]
There's no solution now, no.

That being said, if you have suffixes for "all the others" it's pretty clear that if there's no suffix it will be `fdroid`, I mean if you remove the suffix for what F-Droid builds.

**Comment by LucasGGamerM** [comment]
> There's no solution now, no.
> 
> That being said, if you have suffixes for "all the others" it's pretty clear that if there's no suffix it will be `fdroid`, I mean if you remove the suffix for what F-Droid builds.

The suffix was removed from the f-droid builds. I hope this can make things work out better again :D

**Comment by linsui** [comment]
It works, thanks!

**Comment by LucasGGamerM** [comment]
> It works, thanks!

Even the reproducible builds? :O

**Comment by linsui** [comment]
Yes!
