### ISSUE TITLE
Add Option to remove translation completly from showing

### ISSUE THREAD

**Issue by beautiful-orca** [LucasGGamerM/moshidon#319]
My instance supports translation of posts.
I do not like the translation button, in timeline AND when a post is opened

There is already a option to hide the translate button in timeline but
I would like to have the option to hide it also in a opened post.

For translation I use Translate You from Android context menu which is universal.

**Comment by LucasGGamerM** [comment]
Hmmmm, adding a separate toggle for the translate button is kind of bad, so maybe a menu with 'always, only when opened, never' 

I will see what I can up with

**Comment by LucasGGamerM** [comment]
After some thought, the team decided against adding one more option for this. Disabling the translate button on the timelines is 'enough' for most use cases, and preference overload is starting to become a thing here, so until further thought, this is not gonna happen.
