### ISSUE TITLE
Pleroma 

### ISSUE THREAD

**Issue by s0mt0chukwu** [LucasGGamerM/moshidon#322]
Ability to access any pleroma instance from Moshidon

**Comment by LucasGGamerM** [comment]
You can already do so. What problem have you been experiencing?

**Comment by s0mt0chukwu** [comment]
I can access instances like poa.st but I can't access clubcyberia.co

**Comment by LucasGGamerM** [comment]
It seems like a hostname issue, which is weird, because it works on the browser last time I tried it

**Comment by LucasGGamerM** [comment]
> It seems like a hostname issue, which is weird, because it works on the browser last time I tried it

Nah, I mistyped the instance name, and this looks like a duplicate of #307
