### ISSUE TITLE
Setting "Reduce motion in animations" should affect star rotation

### ISSUE THREAD

**Issue by florian-obernberger** [LucasGGamerM/moshidon#34]
When the setting "Reduce motion in animations" is turned on, the star (the favorite icon) should either not turn at all or turn slower.

**Comment by LucasGGamerM** [comment]
That is indeed a lovely idea

**Comment by LucasGGamerM** [comment]
Fixed in 101e7efd7441cb52fe20fcc36fdfa79acc36871d
