### ISSUE TITLE
Distinguish media card from post content

### ISSUE THREAD

**Issue by naiyerasif** [LucasGGamerM/moshidon#347]
**Is your feature request related to a problem? Please describe.**
Currently, media card (especially one for links without Opengraph Images) blends too seamlessly with a post making it really hard to distinguish it from post content.

**Describe the solution you'd like**
Add some elevation to media card (maybe a subtle background) so that it is clear that it is not the part of post.

**Comment by LucasGGamerM** [comment]
This is a thing that upstream resolved a while ago, and is already a thing with Moshidon on the merge-upstream branch.

Look how nice it is:
![Screenshot_20240308-113724_1](https://github.com/LucasGGamerM/moshidon/assets/71328265/fa1d537b-1245-4c86-bb10-6e72a432f48d)
