### ISSUE TITLE
A glitch or something?

### ISSUE THREAD

**Issue by jotaluissoy** [LucasGGamerM/moshidon#359]
There's something that hasn't been fixed yet to my viewpoint.
Pressing (tapping) a post while scrolling makes this happen:
1. If light mode the post turns close to dark gray.
2. If dark mode, to a glitter light gray.

The rest is okay. Congrats.

Nightly 2024-03-17
mastodon.social

Note: It never happens to Megalodon app.

**Comment by LucasGGamerM** [comment]
Fixed with 14f260d6a110e3f59e8c2c2073696a6e3860b8fb
