### ISSUE TITLE
Filters not working

### ISSUE THREAD

**Issue by kurihoro** [LucasGGamerM/moshidon#37]
Toots that contain the keywords that sould be filtered (and are being filtered on the website and other apps) are not being filtered on moshidon.

1. Create a filter on the website.
2. Go to moshidon app.
3. Check if it works.

Two screenshots are attached: one showing the filter working on the website and other showing the toot that should have been filtered on the moshidon app.

**Version**
Megalodon version:  v1.1.4+fork.85.moshinda (85)

![sks2](https://user-images.githubusercontent.com/44788668/211063533-dee20331-ed7c-478e-8c5c-e0b948780408.jpg)
![sks1](https://user-images.githubusercontent.com/44788668/211063552-f3a9e603-e664-4f3e-86c8-90d2d988d9f9.png)

**Comment by LucasGGamerM** [comment]
Its finally fixed with pre-release number 90!
