### ISSUE TITLE
Wrong tab focus when launching app through notification

### ISSUE THREAD

**Issue by lyfja** [LucasGGamerM/moshidon#388]
**Describe the bug**

When opening the app through a notification and then swiping back, you land on the notification tab. In the bottom however, instead of focusing the notification tab, the home tab is focused instead.

**To reproduce**

1. Receive notification, i.e. User X has liked your post
2. Tap on the notification
3. Swipe back from the page you've landed on (in this case, your post that was liked)
4. Land on the notification tab, but the home tab is focused instead

**Does this happen in the official app?**

The official app behaves differently. When performing step 3, it brings you to your home page and the tab is focused correctly. (v2.5.0)

**Screenshots and screen recordings**
![Screenshot_20240503-155247](https://github.com/LucasGGamerM/moshidon/assets/45209212/7999191e-3942-461e-86e8-dea74a6936ed)

**Version**

Moshidon version: v2.1.4+fork.104.moshinda

**Comment by LucasGGamerM** [comment]
I really hate this bug
