### ISSUE TITLE
Please make collapsed posts without alt-text an option

### ISSUE THREAD

**Issue by joenepraat** [LucasGGamerM/moshidon#393]
In the new version posts that have media without alt-text are collapsed. I find this not very user friendly, because I need to use an extra click to find out what the post is about. It's also unnecessary, because you have indicators that show if media has alt-text or not. Even worse, I can't find an option to disable it. 

So can you please make it at least an option? This is a regression.

**Comment by LucasGGamerM** [comment]
It's already a setting. It's on Behavior -> Show media posts with missing alt text. You can enable it again to fix your issue
