### ISSUE TITLE
Make download/share button more prominent in media viewer

### ISSUE THREAD

**Issue by kyriesk** [LucasGGamerM/moshidon#401]
**Describe the solution you'd like**
After the latest update I noticed that the button to download a image is gone and I can only boost, favourite, share or bookmark. I think downloading images is a very useful feature, is it possible to add it back please?

**Additional context**
If this feature is hidden, please tell me how to turn it back on.

**Comment by LucasGGamerM** [comment]
You need to scroll a bit to see the other options. 

I am working on a better way to deal with the sheet, so don't worry

**Comment by LucasGGamerM** [comment]
It's alright. In the current version the download button is waaaaaay too hidden.

**Comment by LucasGGamerM** [comment]
It's done. The nightlies already have it, and a stable release should have it soon
