### ISSUE TITLE
Push Notification ID compatibility with upcoming Firefish update

### ISSUE THREAD

**Issue by blueset** [LucasGGamerM/moshidon#411]
**Describe the bug**

> A clear and concise description of what the bug is.

I’m a contributor to [Firefish](https://firefish.dev/firefish/firefish), a Misskey fork. I’m currently working on Mastodon API compatibility layer for push notifications in Firefish.

In most Misskey forks, entity IDs are in the form of strings instead of integers. This is fine with the most part of Megalodon and official upstream. However, when processing incoming push notification payloads, the notification ID is parsed as a `long` instead of `string`.

https://github.com/LucasGGamerM/moshidon/blob/c64d6db8592104bfec8022219a6c0b8ea75e330d/mastodon/src/main/java/org/joinmastodon/android/model/PushNotification.java#L14-L17

Despite that, the value is then only used once by converting it back to string in a subsequent API call.

https://github.com/LucasGGamerM/moshidon/blob/c64d6db8592104bfec8022219a6c0b8ea75e330d/mastodon/src/main/java/org/joinmastodon/android/PushNotificationReceiver.java#L103-L104

Parsing the notification ID as `long` would break on Misskey forks with Mastodon API support. I would like to suggest parsing the value as a `string` directly.

**To reproduce**

1. Go to an instance with dev version of Firefish fork with Mastodon push notification support (currently only s.1a23.studio, I can provide account if needed)
2. Receive push notification
3. Observe that parsing of JSON payload fails due to type mismatch at `PushNotification.java:16`.

**Does this happen in the official app?**

> Does this issue also occur with the respective upstream release?
> (Please test using the respective `upstream-xxxxxx.apk` provided in [Releases](https://github.com/sk22/megalodon/releases) or at least using the current Mastodon version from the Play Store)

Yes

> In case it does, please consider filing an [upstream bug report](https://github.com/mastodon/mastodon-android/issues) instead.
> If this bug is seriously impacting your usage or you think I might want to try to fix it for Megalodon, feel free to still create this issue!

~~Since this is a compatibility issue with third-party server programs, it may fall out of scope of upstream project. Please let me know if it is not the case.~~ Filing the same issue to upstream at mastodon/mastodon-android#842 to try my luck. The same issue is also opened with Megalodon at sk22/megalodon#994.

**Screenshots and screen recordings**

> If applicable, add screenshots (and screen recordings, if possible) to help explain your problem.

N/A

**Version**

Moshidon version: [e.g. v1.1.4+fork.#]

v2.3.0+fork.105.moshinda-play

**Crash log**

If you know your way around Android development tools, please consider attaching a crash log, if possible.

N/A

**Comment by LucasGGamerM** [comment]
This is an awesome insight. I see what can be done about changing it tomorrow. 

Thank you for the detailed bug report!

**Comment by FineFindus** [comment]
Since this is also a problem in the official app, have you created an issue there as well? Does the parsing of the payload fail silently, or does it crash the app? In the case of the latter, I would be pretty sure that they would accept a fix, since they have said that [no matter what the server does, the app should not crash](https://github.com/mastodon/mastodon-android/issues/703#issuecomment-1737747370).
Also, since the official docs mention that the [notification ID is a string](https://docs.joinmastodon.org/entities/Notification/#id), it might be in their interest to change it as well, or they might have some insight into why they cast it to a long.

**Comment by blueset** [comment]
> @FineFindus said:
> Does the parsing of the payload fail silently, or does it crash the app?
Technically the parse error throws an exception and crashes the logic. But since it’s running in the background when a push notification arrives, the crash is not visible to the user.

Looking at the example you quoted, it looks promising that upstream maintainers are willing to accommodate third-party servers. I’m filling mastodon/mastodon-android#842 just to tryout my luck. 

Thanks for the suggestion!

**Comment by blueset** [comment]
Dayum, that’s FAST!

Upstream fixed the issue at mastodon/mastodon-android@b2c797fb464a844059b9002bc9189d3ae6874580

**Comment by LucasGGamerM** [comment]
That's grishka man for you. I am cherrypicking the commit asap

**Comment by LucasGGamerM** [comment]
Fixed with ef23734b221ee0ac0ca0581aeb58f90ead3173c4
