### ISSUE TITLE
Show links to other Fediverse posts inline like quotes

### ISSUE THREAD

**Issue by alexanderadam** [LucasGGamerM/moshidon#440]
**Is your feature request related to a problem? Please describe.**

as [mentioned in our conversation](https://ruby.social/deck/@alexanderadam/112701755510129431) it would be great if Moshidon could show links to other Fediverse posts inline.

**Describe the solution you'd like**

Something like [this](https://www.macstories.net/news/tapbots-releases-ivory-1-9-with-quote-posts/) would be nice:
![image](https://github.com/LucasGGamerM/moshidon/assets/372620/1517b0f8-42d7-4946-9f1e-8dda644f4e3d)

**Additional context**

I don't have enough technical expertise regarding the implementation of this feature but according to @renchap, this might be

> [a much more complex feature than showing a preview for a link to a post](https://oisaur.com/@renchap/111925452013048778)

Renaud also [mentions some of the hard questions](https://oisaur.com/@renchap/111925486552542848) that might make this feature difficult:

> - Can you quote a post when replying to someone
> - Is pasting a link into a post quoting? What if there are multiple posts linked?
> - How to handle implementations, instances or clients not supporting quote posts
> - How does this interact with moderation? Blocking?
> - How do we handle ActivityPub implementations with slightly different formats, like if they support quoting multiple posts in the same status?

**Comment by LucasGGamerM** [comment]
Ohhh, so _this_ is the reason why I had a sudden urge to make something like this work. 

I think I should probably close this issue now, as it's already a thing in nightly.
