### ISSUE TITLE
[Bug report] Markdown quotes are not rendered properly in black theme

### ISSUE THREAD

**Issue by Uneccessary** [LucasGGamerM/moshidon#453]

**Comment by LucasGGamerM** [comment]
What does it look like without the pure black theme?

**Comment by Uneccessary** [comment]
Tested it right now and same result. The bar seems to be missing entirely and the text doesn't get gray or anything either.

**Comment by FineFindus** [comment]
This is not a bug, it is supposed to look like this.

**Comment by Uneccessary** [comment]
Oh okay.. thats awkward, I expected it to look something like this:

![image](https://github.com/LucasGGamerM/moshidon/assets/145043411/71218f27-e1db-4947-8f20-058eee1f3f7a)
