### ISSUE TITLE
Clicking translate affects the images 

### ISSUE THREAD

**Issue by maikelthedev** [LucasGGamerM/moshidon#471]
**Describe the bug**

Here's a video https://vmst.io/@maikel/112817288493927484

You scroll in a timeline and click translate and sometimes the images change to previous images on another toots. 

**To reproduce**

Scroll, scroll, press translate. 

**Does this happen in the official app?**

I always use latest nightly

**Comment by FineFindus** [comment]
Duplicate of https://github.com/LucasGGamerM/moshidon/issues/335.
