### ISSUE TITLE
Feature request: swap Hashtags and Posts in Search tab

### ISSUE THREAD

**Issue by danvolchek** [LucasGGamerM/moshidon#472]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
When I open the search tab, I'd like to see posts by default, not hashtags. Changing the order to be posts and then hashtags would do this, and is also the order/behavior the official app uses.

**Describe alternatives you've considered**
Opening posts by default without changing the tab order would work too, but that feels less intuitive.

Settings to choose tabs/order in the search tab would also work, but I don't need that much flexibility.

Thank you for making Moshidon :)

**Additional context**
This is what I'm talking about:

![Screenshot_20240722_083826_Moshidon](https://github.com/user-attachments/assets/5cc9d9df-9599-4c2e-9737-4955ee0d7a4b)

I'd like Posts to be first, and to open automatically when the search tab is opened, rather than Hashtags.

**Comment by LucasGGamerM** [comment]
Yes. This is a thing upstream has already done, so doing it here as well is a no brainer. Thank you for pointing it out!

**Comment by danvolchek** [comment]
Thank you for implementing this! And responding so quickly! I appreciate it :)

**Comment by LucasGGamerM** [comment]
> Thank you for implementing this! And responding so quickly! I appreciate it :)

It was just swapping a few lines of code. Nothing too crazy :P 

But I am indeed glad that you are happy :D
