### ISSUE TITLE
List for severel hashtags

### ISSUE THREAD

**Issue by ikke-t** [LucasGGamerM/moshidon#476]
**Is your feature request related to a problem? Please describe.**
I like the mastodon advanced view column option to have hashtag search filter results pinned to column. Moshidon has now one hashtag per list, please allow to have several. 

**Describe the solution you'd like**
I'd like to have a list item with more than one hashtag as a search term. I'd create e.g. a list named "Home Automation", and group hashtags for it: #HomeAutomation, #HomeAssistant, #ESP etc...

**Describe alternatives you've considered**
Would be perfect if it would fetch such already existing lists from mastodon server's advanced view.

**Additional context**
Check mastodon web advanced view, there is ootion to create such columns.

**Comment by LucasGGamerM** [comment]
Go in the edit timelines menu, click the hashtag timeline you want to add more hashtags to, and click "Advanced", then you will be shown a myriad of options for including and excluding tags, just.like on the web version.

**Comment by ikke-t** [comment]
Uuu, sweet! Thanks and apologies, I had not found that.
