### ISSUE TITLE
Drafted / Scheduled Post overview renders posts wrong

### ISSUE THREAD

**Issue by SteffoSpieler** [LucasGGamerM/moshidon#478]
**Describe the bug**

The view, where you can see all drafted and scheduled posts, doesn't render posts like they should. Formatting (new lines, user-tags, ...) is wrong, and all images are hidden by default.

**To reproduce**

1. Schedule / draft a post, where you do new lines (and other things), and upload an image.
2. See in the overview, that it looks wrong.

**Does this happen in the official app?**

Does this issue also occur with the respective upstream release?
> No (scheduled / drafted posts aren't available in the official Mastodon App)

**Screenshots and screen recordings**

|How it looks in the editor|How it looks in the overview|
|----|-----|
|![Screenshot_20240726-123227](https://github.com/user-attachments/assets/8623be70-79a7-4a34-9655-9be7dad71eb9)|![Screenshot_20240726-123212](https://github.com/user-attachments/assets/32cc6e28-f255-435e-81d8-ca13d1ca11ab)|

**Version**

Moshidon version: 2.3.0+fork.105.moshinda-play

**Comment by LucasGGamerM** [comment]
I wonder how can this even happen

**Comment by FineFindus** [comment]
Unfortunately, fully rendered posts are not possible, since the Mastodon API only returns raw text, and not any formatted content (unlike normal posts) :(

**Comment by SteffoSpieler** [comment]
Hm, interestingly, https://plan.fedilab.app does render the posts a little bit better. (At least there are new lines where they should be.)
![grafik](https://github.com/user-attachments/assets/e6de06b4-5b86-47f3-9a43-803a286ceb26)

**Comment by LucasGGamerM** [comment]
I just wonder what went wrong here. I may need to cool my head a bit to fix this issue

**Comment by FineFindus** [comment]
I am sure that this is going to cause at least a few problems later on...

![Draft correctly rendered](https://github.com/user-attachments/assets/423ff2d6-aea2-4b55-836f-d585d5b3bbfc)
