### ISSUE TITLE
Trending messages not loading (only after swiping to hashtags and back)

### ISSUE THREAD

**Issue by joenepraat** [LucasGGamerM/moshidon#483]
**Describe the bug**

When I click on the magnifier icon, trending messages should appear, but I only see a animated loading icon (keeps loading). When I swipe to hashtags and back, the messages are there. I can now refresh them without issues. Only when I close Moshidon completely and restart Moshidon, the problem re-appears.

**Screenshot**

![Screenshot_2024-07-30-20-12-41-53_0029afb8f6970db29ce334100be72bad.jpg](https://github.com/user-attachments/assets/a58cc3e2-f99f-4987-8e45-5b27c943ed52)

**Version**

Moshidon version: 2.3.0+fork.106.moshinda 

**Crash log**

Not a crash.

**Comment by LucasGGamerM** [comment]
> I also could swear I used to be able to scroll to the top of the trending tab by tapping the magnifying glass icon, like in the official app, but I'm not sure if that's related to this or I'm just misremembering 😅

You actually could, but instead we have decided to enable the double tap to search function by default. If you want to disable it and restore the old behavior, you can just go into Settings -> Display -> And disable Double tap to open search
