### ISSUE TITLE
Broken Download button 

### ISSUE THREAD

**Issue by maikelthedev** [LucasGGamerM/moshidon#486]
**Describe the bug**

One before latest nigtyly release when clicking download just minimises moshidon

**To reproduce**

Check video https://vmst.io/@maikel/112883720903802823

**Comment by TheEssem** [comment]
I'm having this same issue on nightly, whenever an update is available the "Download" button on the update panel just crashes the app.

Crash log: https://paste.evolution-x.org/7SRlZn

**Comment by kescherCode** [comment]
This will only happen on Android 14 or higher.

It happens whenever [`Context.registerReceiver`](https://developer.android.com/reference/android/content/Context#registerReceiver(android.content.BroadcastReceiver,%20android.content.IntentFilter,%20int)) is called without either of the two constants mentioned in the stacktrace.

As such, the following code is affected:

[Code Search results for "repo:LucasGGamerM/moshidon registerReceiver](https://github.com/search?q=repo%3ALucasGGamerM%2Fmoshidon%20registerReceiver&type=code)

**Comment by LucasGGamerM** [comment]
This was just fixed with 249491817179048a2f630a0ef7fe87f9186f5ecb

Lesson learned. I won't update the targetSdk 1 day before the next release :D

**Comment by maikelthedev** [comment]
Well done

Sent from Proton Mail Android

-------- Original Message --------
