### ISSUE TITLE
Better handling of unwanted content in quote posts

### ISSUE THREAD

**Issue by aei86** [LucasGGamerM/moshidon#488]
**Is your feature request related to a problem? Please describe.**
I like the recent introduction of quote posts in the stable release, but unfortunately it ignores blocks, mutes, and *almost* word filters. (This of latest stable & nightly 08/02)

The thing is that if you have someone blocked or muted and another person quotes them, then your preference is ignored and they can appear on any timeline. As for word filters, it still hides filtered words behind a content warning, which is good! but it negates the "Show with content warning" option in the filter.

**Describe the solution you'd like**
In Misskey (a platform with native quote post support) blocking someone mutes any posts from anyone that quote them (at least from my testing?). Some may consider this a destructive option, but I feel it's usable as it's coming from one of the more solid platforms that support quote posting. Same thing with the word filter preference, if "Show with content warning" is off then the quoting post should be hidden.

**Describe alternatives you've considered**
Allow disabling quote posts processing by the app altogether, an option to just to return to the old way moshidon handled quotes (just displaying as an ordinary link prefixed with `RE:`) would work a bit better. Even if it still is inconvenient (unwanted content will still be in your timeline regardless), it'll make it less accessible rather than having filtered posts delivered to your timeline on a silver platter.

**Comment by LucasGGamerM** [comment]
The option to remove the quote posts is actually something I forgot to add in the stable release. 

And your other critism is worth taking a better look onto.
