### ISSUE TITLE
Explore posts not loading 

### ISSUE THREAD

**Issue by MatteoMucchetti** [LucasGGamerM/moshidon#492]
**Describe the bug**
The Posts tab of Search/Explore keep loading indefinitely, showing no posts, until I tap on Hashtag and then go back to Posts.
With this workaround it completes loading almost immediately.

(I am on mastodon.social but I checked also via web and it's not an issue of my server)

**To reproduce**
1. Close and reopen the app (to clear the affected tab content)
2. Go to 'Search'
3. Click on 'Posts' tab
4. See it won't load
5. Click on 'Hashtags' tab
6. Click on 'Posts' tab again and now it works

**Does this happen in the official app?**
Does this issue also occur with the respective upstream release?
> No, not on Mastodon nor Megalodon (although on Megalodon Hashtags is opened as first tab)

**Screenshots and screen recordings**
https://github.com/user-attachments/assets/d4279247-5a8e-40d3-9e42-24783f8b34fb
Just few seconds in this case but it lasts at least few minutes if I don't use that workaround 

**Version**
Moshidon version: 2.3.0+fork.106.moshinda-play (106)

**Crash log**
Not a crash

**Comment by LucasGGamerM** [comment]
Just fixed with f404d2f9cde54f58e64cd56b874c9efb40b66d6f
