### ISSUE TITLE
Difference in releases

### ISSUE THREAD

**Issue by Tealk** [LucasGGamerM/moshidon#494]
Is there a difference between moshidon-fdroidRelease.apk and moshidon.apk ?

**Comment by LucasGGamerM** [comment]
> Is there a difference between moshidon-fdroidRelease.apk and moshidon.apk ?

Yes, there is. The difference is that moshidon.apk is for the github release, while moshidon-fdroidRelease is for the fdroid guys to use as a basis for the reproducible builds.

You can just download moshidon.apk, as that has an autoupdater and doesn't need unifiedPush to have notifications.

**Comment by Tealk** [comment]
So for unifiedPush I use the moshidon-fdroidRelease?

**Comment by LucasGGamerM** [comment]
> So for unifiedPush I use the moshidon-fdroidRelease?

No. Both versions support unifiedPush, but moshidon-fdroidRelease *only* supports unifiedPush

**Comment by Tealk** [comment]
ok thanks for the information.
