### ISSUE TITLE
Feature request: hide emoji button

### ISSUE THREAD

**Issue by PitiBouchon** [LucasGGamerM/moshidon#499]
I would like the ability to hide the emojis which take a lot of space
![Screenshot_2024-08-09-22-49-19-83_0029afb8f6970db29ce334100be72bad.jpg](https://github.com/user-attachments/assets/2cf83e70-fd63-4c1c-9865-2be10bd37df2)

**Comment by FineFindus** [comment]
Settings -> Instance -> Enable Emoji reactions
