### ISSUE TITLE
The translation feature is not working for me

### ISSUE THREAD

**Issue by innosflew** [LucasGGamerM/moshidon#5]
The translation feature is not working for me. Every time I tap on the translate button it gives me an error saying "Not Found". I've tried it with dozens of posts but it doesn't seem to be working anywhere.

![](https://i.imgur.com/MaHy6RJ.jpeg)

**Comment by LucasGGamerM** [comment]
What instance are you on?

**Comment by LucasGGamerM** [comment]
The translation feature only works on instances that support it. Which is why you got the error toast message.

**Comment by innosflew** [comment]
Oh I see. Thank you.
