### ISSUE TITLE
Server blocking???

### ISSUE THREAD

**Issue by yairmohr** [LucasGGamerM/moshidon#504]
For about a week now, I've been unable to use Moshidon, constantly getting error messages claiming my server was down, despite it working perfectly fine in Megalodon.
So I now did a few tests, and I'm starting to suspect all free speech servers have been BLOCKED from being accessed from Moshidon.

Is this true and intentional?

**Comment by LucasGGamerM** [comment]
What server are you on?

**Comment by yairmohr** [comment]
I'm on noauthority.social, but I've tried looking for other servers and noticed poa.st, freeatlantis.com, gameliberty.club, nicecrew.digital and others returning an error message only on Moshidon.

**Comment by FineFindus** [comment]
Moshidon uses the [fedinuke](https://seirdy.one/pb/FediNuke.txt) block list. If your servers are on the block list, you should talk to them about getting them removed.

Also, Megalodon uses the same block list, it just hasn't been updated in a while.

**Comment by yairmohr** [comment]
So this app blocks over 150 servers of the network it's supposed to serve? Great idea for federation!

Never using it again, even if I move instances.

**Comment by LucasGGamerM** [comment]
The blocking is intencional, as there is likely a reason the server in question has been put on the blocklist :(

As there is little we could do (aside from updating the blocklist with a more up to date version), we shall close this issue.

**Comment by briansurratt** [comment]
Why would an app have a block list?   You're taking control away from the user and clearly making decisions about what they can and can't see without indicating why.  If you're going to impede the user experience  with an externally sourced block list at least make it clear the impact.

**Comment by FineFindus** [comment]
> Why would an app have a block list?

I personally have no interest in any code I write being used by people spreading CSAM, hate speech, or other atrocities.

**Comment by yairmohr** [comment]
The problem is many of the 150+ servers on that block list are just harmless, if a bit wacky, places where people are free to say anything legal.

The whole point about the Fediverse is people who don't want to see hate speech or "other atrocities" (since when is any right-wing or religious opinion "an atrocity"? Because as far as I know that's the only "sin" of freeatlantis.com and gameliberty.club) - can block federating with those servers on their own client apps (or their own servers, if they operate them). It's NOT up to app makers or some random guy who puts servers on blocklists without knowing anything about them except there's one user there who wrote one thing the maintainer sees as abhorent.

**Comment by briansurratt** [comment]
> > Why would an app have a block list?
> 
> I personally have no interest in any code I write being used by people spreading CSAM, hate speech, or other atrocities.

The overly broad usage of "atrocities" aside, I understand your concern.  And maybe you're ok with losing users who do NOT want to be constrained by a third party list.

Is it possible for your users to opt out of having that list be applied?

**Comment by LucasGGamerM** [comment]
Not currently, but you can remove blocks.txt and build Moshidon for yourself

**Comment by Eriner** [comment]
You've lost at least two users (that I know of) from my server due to the ideological discrimination of the two of you in your fork of a fork of the Mastodon app. In the face of complaints about servers being blocked after an updating of the Holy Blocklist, rather than reckoning with the fact that the client-side blocklist (from the project you forked) is dumb, @FineFindus doubles down with MuH AtTrOciTiES, and @LucasGGamerM presents a passive, yet negative stance on the issue.

Pathetic.

This shit's dumb.

Just remove the client-side blocklist and stop being babies.

**Comment by LucasGGamerM** [comment]
As much as I'd like everyone to be happy, I don't wish to associate Moshidon with instances that allow intolerance to be spread. Losing a few users from such instances is to be expected, and besides, Moshidon is open source. Just remove the blocklist yourself and use that. 

You won't get an official build without a blocklist as long as I am the BDFL of this project.

**Comment by batumi14** [comment]
It is so absurd and meaningless for such a thing to happen.

**Comment by orestbandera9** [comment]
if anyone here doesnt like this type of shit you should try https://github.com/tipone/seqular-android/releases

it is like if google chrome or firefox implemented a filter for "evil" websites. so ridiculous.
