### ISSUE TITLE
Buggy floating button (auto hide feature)

### ISSUE THREAD

**Issue by BluePixel4k** [LucasGGamerM/moshidon#51]
**Describe the bug**
If I'm scrolling though the feed, the auto hide feature of the floating button is a bit buggy. Sometimes it's jumping down and up quite fast.
See attached video.

**Screenshots and screen recordings**

https://user-images.githubusercontent.com/77979781/213908905-e347761f-5ed0-4b17-940c-b195a4f88a51.mp4

**Version**
Megalodon version: [e.g. v1.1.4+fork.87]

This issue is in relation to this toot: https://floss.social/@BluePixel4k/109729401309219302

**Comment by LucasGGamerM** [comment]
It's fixed on release 88 :)
