### ISSUE TITLE
Option to disable the moving FAB

### ISSUE THREAD

**Issue by MKCOOL142** [LucasGGamerM/moshidon#52]
I find this very irritating to hide the button when scrolling down, I'd much appreciate this to be a thing that you can toggle on and off (mby I just couldn't find the option) instead of a forced thing (this could be another contestant for a future "Advanced" or "Feature Flags" Settings area to prevent cluttering the main settings)

**Comment by LucasGGamerM** [comment]
Yeah, this is long overdue. Working on it right now

**Comment by LucasGGamerM** [comment]
I forgot to close this one, its fixed as of 53d93764b0bcf60617bed21d37dcdbcb2377ff83
