### ISSUE TITLE
Allow to select different default visibility for replies 

### ISSUE THREAD

**Issue by ncravino** [LucasGGamerM/moshidon#57]
**Is your feature request related to a problem? Please describe.**

When I reply to most discussions I usually set the visibility to unlisted. It would be nice to have the ability to set a default for this in the settings akin to what some apps like Fedilab do.

**Describe the solution you'd like**
A entry in the app settings to set the default visibility for replies.

**Describe alternatives you've considered**
The alternative is to either use other app or change it every time I reply to a new discussion. But I like this one, it's stable and smooth.

**Additional context**
![Screenshot_2023-01-26-01-20-23-35_80bdb91ee701dabbcacc59581e333421](https://user-images.githubusercontent.com/12738717/214734142-84933add-52a0-4551-9c73-b69eec201515.jpg)

Edit: added screenshot of one implementation in other app for context

**Comment by LucasGGamerM** [comment]
This one is a lot more useful than I would have thought. It will be there next release!
