### ISSUE TITLE
[idea] text only timelines

### ISSUE THREAD

**Issue by fluoriteByte** [LucasGGamerM/moshidon#579]
**Is your feature request related to a problem? Please describe.**
Sometimes i want to scroll fedi with other people around anot worry about them seeing countless yuri in my timeline

**Describe the solution you'd like**
A Text-only timeline option, like a setting when creating a timeline, where it gets rid of any image (and maybe optionally emojis) and replaces them with their alt texts

**Additional context**
I don't have a mockup screenshot cus im not on my computer to make one

This is a feature i always wanted in a fedi client but haven't found one with it

**Comment by LucasGGamerM** [comment]
That's already a thing you can disable under Settings -> Display -> Show media preview.

After disabling, images, videos and gifs will be replaced with their alt text counter parts, and to see it you need to click on it. 

I will close this as completed

**Comment by fluoriteByte** [comment]
Oh alright
