### ISSUE TITLE
Add a view to follow the local timelines of instances I don't have an account.

### ISSUE THREAD

**Issue by fabioromeo** [LucasGGamerM/moshidon#62]
Moshidon has a menu at the top left that allows you to swipe between my timeline, local and federated ones. It would be awesome if I could also add the local timelines of others instances I'm not logged in - there's many instances like mastodon.art and fosstodon.org that I'd like to follow, but without an account there is kinda cumbersome to follow an user from my main instance.

**Comment by LucasGGamerM** [comment]
This one has actually been implemented in version 96, and is pretty much stable in version 98 (latest for now). I just forgot to close this issue
