### ISSUE TITLE
Load remote followers 

### ISSUE THREAD

**Issue by Mattis142** [LucasGGamerM/moshidon#65]
It seems that currently followers get loaded roughly like this "home_user_instance/@username@foreign_instance/followers" but this only results in followers of the same instance being visible to the user, you can bypass this by opening the profile in the original instances website, so wouldn't it be possible to fetch the follower count from the original server instead? Idk if the API would even allow that since I haven't looked into it tbh

**Comment by LucasGGamerM** [comment]
Closed since v100
