### ISSUE TITLE
redesign external share activity

### ISSUE THREAD

**Issue by MKCOOL142** [LucasGGamerM/moshidon#67]
the current ui has a black background thatlooks fairly odd, instead you should use a transparent activity background and maybe move the menu more to the bottom instead to better emulate the design of the android share sheet

![image](https://user-images.githubusercontent.com/40364718/215532538-ec1f4fd9-4d32-4c60-8263-e942b4a15cbc.png)
![image](https://user-images.githubusercontent.com/40364718/215532551-927e0933-d309-4051-a9b7-22bbbb082651.png)

**Comment by LucasGGamerM** [comment]
Thanks for the model! I will see what can be done

**Comment by MKCOOL142** [comment]
> 

I do know that activities can have transparent backgrounds and appear in front of the last app so it shouldnt be impossible, especially since the external share activity is already a seperate activity 

example:
![Screenshot_20230130-180308](https://user-images.githubusercontent.com/40364718/215544555-9ca70872-b4c8-436a-b4a5-e30be1d6ad5d.png)
