### ISSUE TITLE
Some usernames overly truncated/missing in notifications 

### ISSUE THREAD

**Issue by FakePlasticDunk** [LucasGGamerM/moshidon#71]
**Describe the bug**
Some usernames don't appear in notifications, possibly overly truncated. Doesn't happen in Megalodon (but I only have Megalodon v1.1.5+fork.74-play (74))

**To Reproduce**
1. Go to 'notifications'
2. Scroll down keeping an eye on usernames

**Screenshots and screen recordings**
One from Megalodon, one from Moshidon for comparison
![Screenshot_20230131-181350](https://user-images.githubusercontent.com/123900329/215847979-63fcab97-a618-4f86-a271-b0d5cb77fd52.png)
![Screenshot_20230131-181359](https://user-images.githubusercontent.com/123900329/215847987-a9889000-6f25-4ff5-bd75-88eaff3c9879.png)

**Version**
Moshidon v1.1.4+fork.89.moshinda (89)
Megalodon v1.1.5+fork.74-play (74)
**Additional context**
- Does this issue also occur with the respective upstream release? (Please test using the respective `upstream-xxxxxx.apk` provided in [Releases](https://github.com/sk22/megalodon/releases)) No / Yes (`mastodon#…`)

  > In this case, please consider filing an [upstream bug report](https://github.com/mastodon/mastodon-android/issues) instead. If this bug is seriously impacting your usage or you think I might want to try to fix it for Megalodon, feel free to still create this issue!

**Crash log**
If you know your way around Android development tools, please consider attaching a crash log, if possible.

**Comment by LucasGGamerM** [comment]
In next release, you can untoggle "Enable deleting notifications" and the problem will begone!
