### ISSUE TITLE
Silence an user for an specific period of time

### ISSUE THREAD

**Issue by Andrewblasco** [LucasGGamerM/moshidon#72]
Mastodon web allows you to silence someone permanently or select a period of time untill the silence will expire.
I think it would be a great addition.

I attach an screenshot from Mastodon web (of course, I didn't mute you)

![image](https://user-images.githubusercontent.com/119631423/216137741-194899b4-7fc1-4111-a662-cacc88a16a58.png)

**Comment by LucasGGamerM** [comment]
This one is being worked on by @FineFindus

**Comment by LucasGGamerM** [comment]
This one is fixed, and will be there next update
