### ISSUE TITLE
Change profile UI and organization

### ISSUE THREAD

**Issue by Andrewblasco** [LucasGGamerM/moshidon#73]
Now, Moshidon shows pinned post at a tab of the profile.
Also, it shows the "about" section of a profile in another tab.

Many times, that only hides info that users want to highlight in their profiles.

¿Could we experiment or try another UI for that?
I attach an screenshot for mastodon web organization (Tusky is similar)

![image](https://user-images.githubusercontent.com/119631423/216139343-eb94b65a-5074-4a1d-97ed-6649cb40d33a.png)

**Comment by LucasGGamerM** [comment]
Tusky does it the same way as Moshidon does it, which is why I am not sure how it should be laid out. But thanks for mentioning it!

**Comment by Andrewblasco** [comment]
Well, Tusky at least shows the "About" tab at top profile info like the web:

![image](https://user-images.githubusercontent.com/119631423/216674541-73f3d437-d917-45fa-8310-670ae5fab434.png)

**Comment by LucasGGamerM** [comment]
Ahh, so you mean that... I will see what can be done

**Comment by LucasGGamerM** [comment]
92 fixed this as well
