### ISSUE TITLE
Interface is cuted at new follower notification

### ISSUE THREAD

**Issue by Andrewblasco** [LucasGGamerM/moshidon#76]
When you receive a new notification displaying a new follower, the button that let's you follow back they are cuted.
I think is as simple as reduce the scale of the text about their post, followers and following.

Here you have a demostrative screenshot:

![image](https://user-images.githubusercontent.com/119631423/216676600-ea8666e6-34fe-40f8-ad9d-e8550637457a.png)

By the way, the "Publications" tab at the top in that screenshot it shows an smaller text comparing to "All" and "Mentions" tabs in Spanish. Maybe you can fix also?

**Version**
Moshidon 1.1.4 fork 91

**Comment by LucasGGamerM** [comment]
It's now fixed in the nightly builds. It will also be on the latest stable release!
