### ISSUE TITLE
Little cut in composing screen

### ISSUE THREAD

**Issue by Andrewblasco** [LucasGGamerM/moshidon#77]
When you are at composing screen for a new toot, sometimes the caracters are cutted at the end of a line. It's a minor bug, I hope also has a simple solution =)

I attach an screenshot as example, you can see how the e appears cutted at the end of the line:

![image](https://user-images.githubusercontent.com/119631423/216677663-f1e36a04-8f69-41a4-928c-26e3cf61ab10.png)

**Version**
Moshidon 1.1.4 fork 91

**Comment by FineFindus** [comment]
I think this might be fixed by https://github.com/LucasGGamerM/moshidon/pull/79.

**Comment by Andrewblasco** [comment]
Maybe, I will check in the next update 👌🏼.

**Comment by LucasGGamerM** [comment]
It's fixed
