### ISSUE TITLE
More Material You-izing

### ISSUE THREAD

**Issue by ThatOneCalculator** [LucasGGamerM/moshidon#8]
While having the dynamic colors is definitely nice, it should adhere more to MD3/MY guidelines, such as switches, the bottom navbar, the new post button, material icons, etc

**Comment by LucasGGamerM** [comment]
It's surely a nice proposition, but most of the UI is already quite material you-ish, and it also looks quite pretty. The only part which doesn't look exactly like material you is the settings page. But i feel like it's alright.

**Comment by ThatOneCalculator** [comment]
The bottom bar especially bugs me as it seems to more follow Apple design principles rather than M3.

**Comment by LucasGGamerM** [comment]
Basically no social media apps follow that specific design principle. And it looks cleaner that way.

**Comment by ThatOneCalculator** [comment]
I beg to differ. Kaiteki does a really good job at pulling it off. 

![Screenshot_20221217-065303.png](https://user-images.githubusercontent.com/44733677/208247820-c3ca1a5f-e0de-482d-b207-95a23b5cdecd.png)

**Comment by LucasGGamerM** [comment]
it does look quite good. But the current one is already lovely enough

**Comment by LucasGGamerM** [comment]
Well, I see where you are coming from. But I still stand with the current design principles.
