### ISSUE TITLE
Highlight edit changes

### ISSUE THREAD

**Issue by Mattis142** [LucasGGamerM/moshidon#80]
When looking at the edit history edited characters should be highlighted, if a post is especially long it'd be useful to see which part got changed at first sight, also *IF* the url of a post has been edited it should be automatically expanded and the modified part should be highlighted too since currently you cannot see if the url got edited or not here:
![Screenshot_20230207-211603](https://user-images.githubusercontent.com/40364718/217355738-249b5c75-9875-4915-84b3-65ff202524f0.png)

**Comment by Andrewblasco** [comment]
I also see this it would be useful. BUT, sometimes the edition is something as simple as change the language selected to label your toot... Maybe it is a difficult issue 🤔

**Comment by LucasGGamerM** [comment]
Done as of #297
