### ISSUE TITLE
Make some doubly tackity action with the button on the tabbar 

### ISSUE THREAD

**Issue by LucasGGamerM** [LucasGGamerM/moshidon#83]
Switch tabs after clicking the home/search/notifications tab

**Comment by FineFindus** [comment]
Potential actions:
- Cycle through home timelines
  - Currently, double tapping the Home Timeline scrolls up to the top, in that case a third tap should switch the timeline
- Switch notification tabs
- Switch profile tabs?

**Comment by LucasGGamerM** [comment]
Hey, so there is an issue with this. The show new posts button is broken. It does not scroll to the top if the setting is enabled, and instead cycles through everything
