### ISSUE TITLE
Publish button text invisible in Nord theme 

### ISSUE THREAD

**Issue by FineFindus** [LucasGGamerM/moshidon#84]
**Describe the bug**

The publish button text is invisible when the Nord theme is applied. 

**To reproduce**

1. Go to settings, apply Nord theme, make sure the publish button is not relocated 
2. Click on Compose new fab
3. See empty publish button 

**Screenshots and screen recordings**

![empty publish button](https://user-images.githubusercontent.com/63370021/217666798-cb31bf1b-2c06-46b0-8d9f-9960353e9088.jpg)

**Version**

Moshidon version: v1.1.4+fork.92.moshinda

**Comment by LucasGGamerM** [comment]
Its probably a color that is off... Should be easy to fix

**Comment by LucasGGamerM** [comment]
Tis fixed. The contrast is still a little low, but its now visible
