### ISSUE TITLE
New icon discussion. (Name is alright and I don't plan to change jt)

### ISSUE THREAD

**Issue by LucasGGamerM** [LucasGGamerM/moshidon#90]
Discussion for a new icon down below

**Comment by LucasGGamerM** [comment]
I have just found out Moshidon is a dish, I guess we have something here

**Comment by MKCOOL142** [comment]
I know you don't want to change the name but smilodons are pretty cool >~<
![Smilodon Knight](https://user-images.githubusercontent.com/40364718/219467059-d8926bbb-edee-4a1c-b690-2c3dede2bd92.jpg)

**Comment by LucasGGamerM** [comment]
![Screenshot_20230216-165109](https://user-images.githubusercontent.com/71328265/219472075-3d6aa881-09f6-42f9-9401-889ebb6acd11.png)
This is how I have tweaked for now

**Comment by LucasGGamerM** [comment]
Lets just say Mo looks dope
